### ISSUE TITLE
[Bug/Compatability] Item Pipes don't seem to insert

### ISSUE THREAD

**Issue by Dragnier** [RootsTeam/Embers#101]
I connected an item pump to an Actually Additions Farmer and it extracted the items. However, the pipes didn't insert things into the Storage Drawer or Canola Press. They just sat there doing nothing. I broke all the pipes and the items re-appeared in the Farmer.

MC: 1.11.2
Forge: 13.20.0.2226
Embers: 0.107

**Comment by elucent** [comment]
I believe this is due to a bug that I very recently fixed.
