### ISSUE TITLE
[Bug - 1.11.2] Melter uses Ember even when last ore is smelted

### ISSUE THREAD

**Issue by Dragnier** [RootsTeam/Embers#106]
I've noticed that the Melter gets stuck looking like one ore is always in it even after the last ore is smelted. This apparently also cause it to continuously suck up ember until you right click it either with an empty hand or to put more ore into it. Empty hand right click clears the phantom ore and stops it from using Ember.

**Comment by elucent** [comment]
Huh, I thought I fixed this. I'll get to it soonish.

**Comment by elucent** [comment]
I believe I fixed this and forgot to close this issue.
