### ISSUE TITLE
Clockwork Tools and Grandhammer's right click function not working in 1.11.2

### ISSUE THREAD

**Issue by MystiMayhem** [RootsTeam/Embers#112]
They all work as tools fine, but nothing happens on right click. This is with version 0.107 and version 0.201.

**Comment by elucent** [comment]
Yes, it was removed. I plan on giving them a new functionality in the near-ish future.

**Comment by MystiMayhem** [comment]
My mistake then, thanks for the clarification. Love your work, btw.
