### ISSUE TITLE
(Technicality) One glaring issue with Chisels&Bits

### ISSUE THREAD

**Issue by Yoghurt4C** [RootsTeam/Embers#114]
Current block class "structure" - at least in 1.11.2 - makes all Embers (and Roots) blocks not suitable for using with C&B.

**Comment by codewarrior0** [comment]
For reference, here's the long list of requirements C&B has for making a block into bits:

https://github.com/AlgorithmX2/Chisels-and-Bits/blob/1.10.2/src/main/java/mod/chiselsandbits/chiseledblock/BlockBitInfo.java#L185

At a glance, I'm not sure which of them BlockBase is violating.

**Comment by elucent** [comment]
This has been fixed in v0.203!
