### ISSUE TITLE
[1.11.2] World gen crash

### ISSUE THREAD

**Issue by Terpo** [RootsTeam/Embers#115]
Hello, 
I'm currently trying some things in a void world but sometimes it crashes. 
Current config for worldgen stuff: http://pastebin.com/vzB6vmSv
Crashlog: http://pastebin.com/LXNB8qu4

Playing on 1.11.2 with Forge build 2230 and embers-0.201

The world is a simple flat world with custom preset
3;minecraft:air;,

**Comment by drakray** [comment]
Came to report the same [crash](http://pastebin.com/c4Xt2ZNS)

**Comment by elucent** [comment]
This is my fault, will fix shortly.

**Comment by elucent** [comment]
Fixed, will be in the next release within days I hope.
