### ISSUE TITLE
Paralyzed by Item Pipe update packets

### ISSUE THREAD

**Issue by codewarrior0** [RootsTeam/Embers#117]
```
embers-0.201.jar
forge-1.11.2-13.20.0.2252
```

Playing in multiplayer, the server is experiencing >1000 ms lag and my client's FPS dropped to the single digits. Sampling with VisualVM points a finger at TE update packets for the item pipes:

![image](https://cloud.githubusercontent.com/assets/307683/23643061/5e7324f8-02a3-11e7-8cf2-63c6fc36d0bc.png)

Full mod list: https://gist.github.com/codewarrior0/466eff38044e97c528ea50b6dd0f27d2

**Comment by elucent** [comment]
I might have fixed your problem in the next update. It'll be out pretty soon, within a few days I'd expect. Sorry for the issues!
