### ISSUE TITLE
[0.201] Concurrent nullpointer exception when player leaves game on server

### ISSUE THREAD

**Issue by Rosethorns** [RootsTeam/Embers#119]
Minecraft: 1.11.2
Forge: 13.20.0.2252
Embers: 0.201

Not entirely sure it is specifically Embers, but it is the mod named in the first error call.
First error call excerpt:
http://pastebin.com/N4rnFGvg

Full log:
http://pastebin.com/J4iqU0t3

**Comment by elucent** [comment]
I believe this is my fault, should have a fix out later today. Let me know if it's fixed!
