### ISSUE TITLE
[1.11.2] Rendering block entity crash - Breaker.

### ISSUE THREAD

**Issue by MrNinja93** [RootsTeam/Embers#120]
Died in game and on re-spawning crashed to desktop.

Probably partly (or entirely) caused by the breaker being attached to a sticky piston. (Edit: Piston was extended)

CrashLog: https://gist.github.com/MrNinja93/70d991016e06ae938df28912badece1c

Forge: 13.20.0.2252
Embers: 0.201

**Comment by elucent** [comment]
I think I've fixed this, will be out in the next update.
