### ISSUE TITLE
Breaking the bottom block of a two block tall structure duplicates it with Psi.

### ISSUE THREAD

**Issue by PetersonE1** [RootsTeam/Embers#121]
If I break the bottom of a two block tall structure with a break block spell from Psi, such as the melter, both blocks drop the item, thus duplicating it.

embers 0.201
forge-13.20.0.2233
minecraft 1.11.2

**Comment by Flabort** [comment]
Interesting mod interaction. It will be interesting to see which mod is at fault.

**Comment by elucent** [comment]
Strange. I think I can implement a fix for this on my side, but I'm not certain.

**Comment by elucent** [comment]
Should be fixed, I think. Will be in a release soon.
