### ISSUE TITLE
Clockwork pickaxe etc. not respecting cancelled events

### ISSUE THREAD

**Issue by KasperFranz** [RootsTeam/Embers#123]
This is mainly happening when mining in to a claimed area, where you are not allowed to (with like griefprevention on a SpongeForge server)

the way to do it is just to have another player claim the area and then if you try to mine stuff, Like a chest - the chest and content pops out but it also stays in place with the end result of doubled items.

**Comment by elucent** [comment]
Which Minecraft version, which Embers version, and most importantly is this on a Sponge server? Sponge and Embers in 1.11.2 do not mix well.

**Comment by KasperFranz** [comment]
Sorry abotu that

It is on MC 1.10.2  and using ember 0.104

**Comment by bookerthegeek** [comment]
@elucent I'll test this for you wout tomorrow and go cross post it over at sponge. They are pretty good at either fixing it on their end or figuring out how to make it work from yours.

**Comment by elucent** [comment]
I'm not maintaining the 1.10.2 branch of Embers regardless. I'll leave the issue open in case I ever change my mind, but don't expect a fix.

**Comment by elucent** [comment]
Closing this due to 1.10.2 no longer being supported.
