### ISSUE TITLE
Improved OreDict Support for Alchemy

### ISSUE THREAD

**Issue by the-realest-stu** [RootsTeam/Embers#125]
The oredict support for alchemy added in 0.202 work quite differently from other types of oredict recipes, which tend to use strings to represent any item with whatever oredict entry you want, instead of using itemstacks and then checking if they have any oredict-compatible counterparts. It isnt a necessary change, but would be nice for consistency, and I think it may be necessary for making JEI show all oredicted items in the recipe, although that would also take a few tweaks to the jei compat for alchemy.

Also, after testing alchemy in 1.11, it seems to work at first, but then all the outer ingredients disappear from the recipe itself. Not the alchemy table, but the recipe itself, as seen in jei. I noticed this after trying to make a copper seed with forestry copper. So it seems as though you might need to look into fixing alchemy anyway.

**Comment by elucent** [comment]
Fixed this, will be in the next release.
