### ISSUE TITLE
NPE Crash when using Clockwork Pickaxe on Netherbrick

### ISSUE THREAD

**Issue by tommyTT** [RootsTeam/Embers#129]
**Issue Description:**
The game crashes with a NPE when I try to mine certain blocks (e.g. Netherbricks or Magma Blocks) with the Clockwork Pickaxe.

**What happens:**
Game completely crashes.

**What you expected to happen:**
Being able to break these blocks normally.

**Steps to reproduce:**
Get a Clockwork Pickaxe and a cartridge to provide the ember. Try to mine a block of nether bricks in survival mode.

**Affected Versions:**
Minecraft: 1.11.2
Forge: 13.20.0.2259
Mods:
  embers-0.205
  jei_1.11.2-4.2.10.248

**Your most recent log file where the issue was present:**
https://paste.ee/p/ndb5m

**Further notes:**
It looks like the Embers code [here ](https://github.com/RootsTeam/Embers/blob/master/src/main/java/teamroots/embers/item/ItemClockworkPickaxe.java#L101) reads the harvest tool from the block by calling the Block.getHarvestTool() method which can return null. The method ItemTool.getHarvestLevel() however doesn't expect the provided toolClass parameter to be null (the interface doesn't seem to allow that) and therefore crashes the game.

**Comment by elucent** [comment]
Same issue as #133 , should be fixed in the next release. I'll close this, follow that issue thread if you have further comments.
