### ISSUE TITLE
Dawnstone anvil returns items with broken textures

### ISSUE THREAD

**Issue by tommyTT** [RootsTeam/Embers#130]
**Issue Description:**
When using the dawnstone anvil to break down items into their respective crafting parts it gives items that don't have a texture.

**What happens:**
Using the dawstone anvil to "uncraft" items (e.g. an iron helmet) results in items with broken textures.

**What you expected to happen:**
The returned items are "normal" items with their usual textures and not the "missing texture" texture.

**Steps to reproduce:**
1. Put down a dawnstone anvil.
2. Put a vanilla minecraft iron helmet onto the anvil.
3. Hit the anvil with the tinker's hammer until the helmet is uncrafted into 5 iron ingots.

**Affected Versions:**
Minecraft: 1.11.2
Forge: 13.20.0.2259
Mods:
  embers-0.205
  jei_1.11.2-4.2.10.248

**Your most recent log file where the issue was present:**
https://paste.ee/p/m61dz

**Comment by elucent** [comment]
Do you have Sponge installed by any chance?

**Comment by tommyTT** [comment]
No, just Forge with Embers and JEI installed.

**Comment by elucent** [comment]
Hmmmm. I haven't experienced this myself. What items in particular? Is it all items?

**Comment by tommyTT** [comment]
I can't say it is _all_ items, I have tested it with a vanilla iron helmet and a vanilla diamond helmet and both itemstacks had the broken texture. I haven't tried any none armor item yet, but I can do more testing later today, maybe I can give you further information. Any particular item that I should test with?

**Comment by tommyTT** [comment]
I tested and debugged it further and found the problem. The iron ingots that the anvil spawns have the meta data value of 32767 which is the ore dictionary wildcard value from Forge (net.minecraftforge.oredict.OreDictionary.WILDCARD_VALUE) and therefore the model can't be found. I don't understand why this doesn't happen for you.
The solution would be to check the repair item stack for the wildcard value and use 0 as the meta instead.

**Comment by elucent** [comment]
Yes, I can implement that fix. Just odd that it's occurring in the first place.

**Comment by elucent** [comment]
Closing now, should be fixed in the most recent release.
