### ISSUE TITLE
Server crash when using the Auto Hammer on the Dawnstone Anvil

### ISSUE THREAD

**Issue by tommyTT** [RootsTeam/Embers#131]
**Issue Description:**
Using the auto hammer on the dawnstone anvil on a server will crash the server when trying to "uncraft" a piece of armor because of a NoSuchMethodError. Works perfectly in single player.

**What happens:**
I'm trying out the auto hammer on the dawnstone anvil when on a server but it keeps crashing the server when I give it a piece of armor.

**What you expected to happen:**
In a single player world the hammer works perfectly, so this should also be the case on servers.

**Steps to reproduce:**
1. Have a dedicated server world with Embers.
2. Setup the Auto Hammer next to the Dawnstone Anvil. Feed it the required ember.
3. Put a vanilla minecraft iron helmet onto the anvil.
4. Give a redstone signal to the hammer, so it starts working.

**Affected Versions:**
Minecraft: 1.11.2
Forge: 13.20.0.2259
Mods:
  embers-0.205
  jei_1.11.2-4.2.10.248

**Your most recent log file where the issue was present:**
https://paste.ee/p/wJcUu (crash report)
https://paste.ee/p/I7N2I (latest server log)

**Further notes:**
The method [Misc.getResourceCount()](https://github.com/RootsTeam/Embers/blob/master/src/main/java/teamroots/embers/util/Misc.java#L114) uses the ItemArmor.getEquipmentSlot() method to determine an amount of the resources to return, but that method is annotated with @SideOnly(Side.CLIENT) and therefore not available on servers. However, the field this method returns seems to be public anyway, so direct access would be a "solution".

**Comment by elucent** [comment]
Should be fixed in the most recent release.
