### ISSUE TITLE
unable to use Clockwork Tool right click functionality.

### ISSUE THREAD

**Issue by GeekBeam** [RootsTeam/Embers#132]
not sure what is causing the issue, but it crops up with Embers v0.205.

one is entirely unable to use right click functionality of Clockwork tools within that version, had both Mantle cartridge, and Mantle Jar in inventory.

MC 1.11.2
Embers v0.205

**Comment by Qohelethh** [comment]
Why is this closed? I am having the same issue.

**Comment by elucent** [comment]
Because the right-click functionality was intentionally removed. It will be replaced with something eventually.

**Comment by Qohelethh** [comment]
Thanks!
