### ISSUE TITLE
Clockwork Pickaxe crash when mining Quark bloicks

### ISSUE THREAD

**Issue by GeekBeam** [RootsTeam/Embers#133]
not quite sure if these crashes were caused by JEI not knowing what the harvest level of the mined item was, but The One Probe seems to predict the crash quite handily, going to the "default" or "fallback" information for the block.
the first crash, I was holding a constellation paper in hand: [puush](https://puu.sh/uPLtT/514694c679.txt)
the second crash, I was holding a torch in the offhand:  [puush](http://puu.sh/uPLDa/4e64ba01bb.txt)

**Comment by GeekBeam** [comment]
the crash seems to be more specific to Quark's Marble, if that is at all important

**Comment by VallenFrostweaver** [comment]
I can verify. This is also in version 1.11.2 Minecraft and most recent versions of Embers and Quark.

**Comment by elucent** [comment]
This is a little odd, I have gone to the line of code which errors and I don't _think_ I'm doing anything wrong.

Regardless, I believe I've changed this to something that should be foolproof. I'll close this when I get the next build out, let me know if it didn't actually fix things.

**Comment by elucent** [comment]
Will close this now, should be fixed in the latest release.
