### ISSUE TITLE
[1.11.2] Beam Splitter will eat ember even if its destinations are full.

### ISSUE THREAD

**Issue by Rosethorns** [RootsTeam/Embers#136]
Description:
Ember Beam Splitter appear to infinitely eat up ember even if both its outputs are full.
The splitter stops sending ember but any new ember entering the splitter is eaten regardless.

Repeat:
1. create ember source.
2. link it to beam Splitter.
3. link Beam Splitter to two receiving sources.
4. Beam Splitter will inevitably fill up its destinations and stop. But Ember will continue to be sent to it.

Versions:
Minecraft: 1.11.2
Forge: 13.20.0.2252
Embers: 0.205

**Comment by elucent** [comment]
Fixed this just now, will be in the next build.

**Comment by elucent** [comment]
Should be fixed in the most recent release.
