### ISSUE TITLE
[1.11.2] Complex Alchemy Bug, Video Inside. Infinite reaction, changed recipe. wrong aspectus

### ISSUE THREAD

**Issue by Rosethorns** [RootsTeam/Embers#137]
Ember Alchemy. Any recipe with “side” resources, will not work the first time. The Ash will be used from the pedestals but the event will never complete the beams will continue and the circle will be there rotating.
Removing the resources or Aspectus will not stop it. The only course of action is to break the exchange tablet.
Strangest of all. After breaking the tablet the recipe in NEI will change to /just/ the center item.
From that point on the recipe will actually work. But only with the center item.
Secondary. The Aspectus required in NEI will sometimes be wrong. And the failed experiment will list the actual required aspectus by showing inaccuracy.

Example. 

1.Ashen cloth never stopped being created with 2 string 2 ash and 1 wool, an iron and silver aspectus (as according to NEI)
After breaking the Exchange Tablet, the recipe then showed the ashen cloth as being /only/ wool, and iron and silver aspectus.
After the recipe failed correctly and produced a failed experiment. It showed that the aspectus required was iron and lead.

For a specific demonstration please see the video linked here https://www.youtube.com/watch?v=owGH7jsRErw

Versions:
Minecraft: 1.11.2
Forge: 13.20.0.2252
Embers: 0.205

**Comment by elucent** [comment]
I think I may have already fixed this, but I'm not entirely sure. When I get the next build out, could you let me know if it's fixed? I can no longer replicate this bug in my dev environment but at the same time that doesn't necessarily mean anything.

**Comment by Rosethorns** [comment]
Will do :)

**Comment by elucent** [comment]
Should be fixed in the most recent release.
