### ISSUE TITLE
[1.11.2 - 0.205] putting Ashen Cloak into crafting grid to extra inflictor gems causes crash.

### ISSUE THREAD

**Issue by GeekBeam** [RootsTeam/Embers#139]
have an Ashen Cloak filled with 7 inflictor gems of damage type :OnFire, attempting to put the single item into a crafting grid results in a crash

[Crashlog](http://puu.sh/uS12k/f5e51cdaf8.txt)

**Comment by elucent** [comment]
Closing now, should be fixed in the most recent release.
