### ISSUE TITLE
[0.007] Ores mine too fast

### ISSUE THREAD

**Issue by Alsender** [RootsTeam/Embers#14]
Forge Version: 12.18.2.2099

Embers ores mine too fast.  Copper ore mines faster than stone when using a stone pick.  Silver and lead both mine at about the same speed as iron ore when using a stone pick.  All three mine at the same pace as stone when mined by hand.  This can be especially problematic when testing what level pick can mine up which ores, as at first test, it would seem that stone can mine silver and lead, because the ore does not take any longer than you would expect to mine, only to realize that you did not get anything from it.

**Comment by elucent** [comment]
I left the hardness values intentionally low so the ores would be convenient to mine, but I'll raise them now so they don't confuse anybody.
