### ISSUE TITLE
[1.11.2] Manual text is unreadable when enforcing unicode font

### ISSUE THREAD

**Issue by 3TUSK** [RootsTeam/Embers#141]
Byproduct of testing #140. See picture below (note: fullscreen can't alleviate problem):
![image](https://cloud.githubusercontent.com/assets/9113033/24127336/24baf238-0daa-11e7-9480-c7df9e80a561.png)
![image](https://cloud.githubusercontent.com/assets/9113033/24127341/32353252-0daa-11e7-9ad3-e946b1def247.png)

For anyone who may ask "why not just turn that off": not possible when game sets its locale to Simplified Chinese (`zh_CN`), as that option will have no effect after setting locale to `zh_CN`. 

For me that's not really a big deal, but considering about the fact that not all players are fluent in English, as well as some past examples (e.g. Ellpeck/ActuallyAdditions#461, ForestryMC/ForestryMC#776, OpenMods/OpenBlocks#621), I still consider this as a design flaw and thus decide to write an issue ticket. 

> I also tried to fix that, but failed. Not skilled enough to find the proper offset.

**Comment by elucent** [comment]
The eye was removed several versions ago. Let me know if this still happens with the Codex, though I believe it should not.

**Comment by 3TUSK** [comment]
Wait, *several versions ago*? What I cloned is outdated codes?

**Comment by elucent** [comment]
I'm...not great at keeping GitHub up to date. And for some reason a lot of my changes aren't making it to the master branch. I'll figure it out.

**Comment by 3TUSK** [comment]
> ¯\_(ツ)_/¯

Still, thanks for quick reply.

**Comment by elucent** [comment]
Found the issue with my GitHub, should be syncing properly now.

**Comment by 3TUSK** [comment]
Yup, this issue is invalid for Codex. Thanks for bring Embers!

**Comment by elucent** [comment]
Tis. I'll update it eventually.
