### ISSUE TITLE
[1.11.2  v0.205] Fluids in machines and buckets

### ISSUE THREAD

**Issue by vail0n** [RootsTeam/Embers#143]
Machines that acept liquids doesn't empty/fill buckets and can continuously get filled/emptied.

Minecraft 1.11.2
Embers 0.205
Forge 13.20.0.2259

![vessel](https://cloud.githubusercontent.com/assets/26553642/24148608/a4c91300-0e50-11e7-8b87-3f1743a67607.gif)

**Comment by elucent** [comment]
Fixed in v0.206, but CurseForge is taking a while to approve the version. Sorry! Just be patient, at this point it's out of my control.
