### ISSUE TITLE
Gauges accessing capability from wrong facing

### ISSUE THREAD

**Issue by Choonster** [RootsTeam/Embers#144]
The `facing` property of the gauge blocks (Fluid Gauge and Ember Gauge) indicates which direction the gauge is facing towards and also which side of the neighbouring block it's attached to. Despite this, they access the capability from the **opposite** facing of the neighbouring block in their implementation of `IDial#getDisplayInfo`.

This means that a gauge attached to the west side of a block (i.e. `facing` is `EnumFacing.WEST`) will try to access the capability from the east side (i.e. `EnumFacing.EAST`).

To reproduce this:
* Place a block that only provides the `IFluidHandler` capability from specific sides (e.g. EnderIO's Fluid Tank, my mod's [Restricted Fluid Tank](https://github.com/Choonster/TestMod3/blob/4052374ab3f6da71669ccf3624034768444ed6e4/src/main/java/choonster/testmod3/tileentity/TileEntityFluidTankRestricted.java) or Astral Sorcery's Lightwell).
* Test or configure which facings allow access to the `IFluidHandler` capability.
* Fill the tank with some fluid.
* Place the Fluid Gauge on a side of the block that allows access and opposite to a side that doesn't. Note that it doesn't display the tank's contents when you mouse over it.
* Place the Fluid Gauge on a side of the block that doesn't allow access and opposite to a side that does. Note that it displays the tank's contents when you mouse over it.

Side note: `EnumFacing#getOpposite` should work for any facing, including `UP` and `DOWN`. `Misc.getOppositeFace` shouldn't be needed.

**Comment by elucent** [comment]
I had issues with EnumFacing.getOpposite in the past, so I just wrote my own. No real issue either way.

Anyway, thanks for bringing this up! I do have to ask: which Embers version? If it's a 1.10.2 one I may have already fixed it -- I have some memory of finding this bug but I may have forgotten to actually implement the fix.

**Comment by Choonster** [comment]
The issue is present in the master branch. I reproduced it with Embers 0.206.

**Comment by elucent** [comment]
Yes, I realized that, it'll be fixed for 0.207.
