### ISSUE TITLE
[1.11.2 - 0.206] Further ClockWork tool Issues.

### ISSUE THREAD

**Issue by GeekBeam** [RootsTeam/Embers#145]
the crash issue still exists with the clockwork Axe in particular (it produces the error when you attempt to even poke anything that crashed the clockwork pick beforehand, including vanilla furnaces.)

the ClockWork Pickaxe, where it simply crashed before, is entirely unregistered as even _being_ a pickaxe at all with these wildcard blocks. (Quark Marble is not harvestable, as a singular example, ALL other cases where the crash would occur beforehand mirror this case)

continuation of this issue's bugs, most tools besides the clockwork pick still have the crash problem that this issue describes: https://github.com/RootsTeam/Embers/issues/133

**Comment by Cal26lum** [comment]
Additionally, the grandhammer does not seem to cause anything to drop from blocks.

**Comment by GeekBeam** [comment]
@cal26lum this is an intended effect. Check your codex.

**Comment by Cal26lum** [comment]
Sorry, I didn't realise that "smash blocks into nothing" was quite so literal. In that case, why can fortune be applied?

**Comment by GeekBeam** [comment]
Same reason you can apply fortune to a pick, an axe, qnd a shovel. The grandhammer counts as all three of those tools at once, it just gives no harvested blocks from them

**Comment by Cal26lum** [comment]
Fair enough. Good to know, thanks

**Comment by elucent** [comment]
The crash has been fixed in my dev environment, I just need to finish up some content.

**Comment by Ayrrow** [comment]
Can I extend this? My clockwork pickaxe doesn't count as a hammer when breaking a vanilla hopper, so breaking a hopper with the pickaxe doesn't return a hopper. 

![2017-03-27_16 12 44](https://cloud.githubusercontent.com/assets/7918443/24343421/1bdaa0ec-1312-11e7-9138-06c23aa2fb4e.png)
![2017-03-27_16 12 51](https://cloud.githubusercontent.com/assets/7918443/24343422/1be88f2c-1312-11e7-9902-c2969b70c6ee.png)

**Comment by GeekBeam** [comment]
This is already a known part of the issue, Elucent should have it fixed by next update
