### ISSUE TITLE
emitters and receptors not working for me

### ISSUE THREAD

**Issue by LocoMinerDad** [RootsTeam/Embers#147]
I am sure I am missing something. I watched the video and did what they did. I have a activator. It has ember in it. I attached a emitter with a level and the power is on. I have a copper cell with a receptor. I right clicked my hammer on the receptor then the emitter but nothing is happening. 

Minecraft 1.11.2 forge .2259, mod .206

**Comment by ApeSpork** [comment]
Having the same issue, same setup. I am on Minecraft 1.10.2 using embers 0.104. Activator with ember, emitter then receptor on the side of copper cell, shift-right clicked receptor with tinker hammer then emitter, put lever on emitter and switched it on.  No ember being transferred, no particle effect.

**Comment by LocoMinerDad** [comment]
I tried every version from current to 201 and it doesnt work.

**Comment by Cal26lum** [comment]
You have to shift click the receptor, and then regular right click the emitter

**Comment by elucent** [comment]
What Cal26lum said.
