### ISSUE TITLE
Blades on bottom of ember bore not spinning

### ISSUE THREAD

**Issue by ApeSpork** [RootsTeam/Embers#148]
I have put an ember bore down 3 blocks below bedrock. It is powered with coal and is producing ember; however, the blades are not spinning, just twitching.

![2017-03-26_13 43 04](https://cloud.githubusercontent.com/assets/26693536/24333692/9b30d6f6-122a-11e7-800e-0075fb7645d1.png)

**Comment by elucent** [comment]
This bug was fixed in 1.11.2, and 1.10.2 is no longer being maintained. It is purely aesthetic.
