### ISSUE TITLE
Large machines and block breakers

### ISSUE THREAD

**Issue by Cal26lum** [RootsTeam/Embers#149]
Machines such as the ember bore have some strange results when used with block breakers (even embers own). They cause a small lag spike, and then return a tile.mech_edge.name. Additionally, with recent quark versions, pistons do similar things. 

It's certainly not a major issue, but I thought I would bring it to your attention anyway.

**Comment by elucent** [comment]
Yeah, they don't break blocks in the best way. I'll fix it up eventually.
