### ISSUE TITLE
Suggestion: Make pumps only extract from the inventory they're placed on.

### ISSUE THREAD

**Issue by laserlemons** [RootsTeam/Embers#15]
In this picture, I placed the pump against the bin. It'd be nice if it'd extract from the bin and insert into the Ember Activator instead of trying to extract from both. Maybe it could also be configured using the Tinker's Hammer?
![2016-10-12_15 56 24](https://cloud.githubusercontent.com/assets/6501298/19330653/915861fc-9094-11e6-8818-bffb5d3eded0.png)

**Comment by elucent** [comment]
This was implemented and I forgot to close this.
