### ISSUE TITLE
[1.11.2 - 0.206] [RaxPack 2] Alchemy Recipes not working

### ISSUE THREAD

**Issue by Ayrrow** [RootsTeam/Embers#150]
**Updated - now had time to test multiple recipes; none worked.**

Placed Glowing Crystal recipe according to JEI, Beam Cannon is targeting the exchange tablet. Beam Cannon has 2000/2000 ember according to the gauge attached. Correct aspectus and minimum of 64 ash inserted into Alchemical Construct. 

![2017-03-28_23 58 36](https://cloud.githubusercontent.com/assets/7918443/24407841/cbcab798-1417-11e7-830c-f4ec8cd3ef43.png)
![2017-03-28_23 58 38](https://cloud.githubusercontent.com/assets/7918443/24407842/cbd2f188-1417-11e7-9657-7f853fbd77fe.png)
![2017-03-28_23 58 40](https://cloud.githubusercontent.com/assets/7918443/24407846/cbf99da6-1417-11e7-8088-0981c893fa90.png)
![2017-03-28_23 58 50](https://cloud.githubusercontent.com/assets/7918443/24407844/cbd71a06-1417-11e7-976f-3ffdcdfa8d16.png)
![2017-03-28_23 58 35](https://cloud.githubusercontent.com/assets/7918443/24407843/cbd30b46-1417-11e7-96b3-2c943d5a3134.png)

**Comment by elucent** [comment]
Does the cannon have redstone power?

**Comment by Ayrrow** [comment]
Yes the cannon had redstone power. I've tested both with and without signal. Just a heads up the codex says nothing about a redstone signal.

**Comment by Ayrrow** [comment]
Just tested in a creative world and it works fine so I'm assuming Ive done something wrong in my actual world. I can't access that at the moment because of a crash from another mod but when I can I will break everything and see if that fixes the issue

**Comment by Ayrrow** [comment]
Breaking everything and replacing seems to have fixed this issue
