### ISSUE TITLE
[1.11.2 - 0.206] [RaxPack 2] Crash to desktop when left-clicking a chisel block with a Clockwork Axe

### ISSUE THREAD

**Issue by Ayrrow** [RootsTeam/Embers#152]
As per title. I've attached a full log. 

> ` ---- Minecraft Crash Report ----
> 
> WARNING: coremods are present:
>   SHLoadingPlugin (ScalingHealth-1.11.x-1.0.5-47.jar)
>   LoadingPlugin (Quark-r1.2-88.jar)
>   AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
>   ForgelinPlugin (Forgelin-1.4.0.jar)
>   RebornCoreASM (RebornCore-1.11.2-2.13.5.42-universal.jar)
>   DummyPlugin (ForgeEndertech-1.11.2-2.0.7.0-build.0017.jar)
>   CorePlugin (FluxedRedstone-2.6.0.54.jar)
>   CXLibraryCore (cxlibrary-1.11.2-1.4.0.jar)
>   llibrary (llibrary-1.7.4-1.11.2.jar)
>   ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.3.jar)
>   Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-beta2-anarchy.jar)
>   literalascension (literalascension-1.11.2-1.0.1.1.jar)
>   IvToolkit (IvToolkit-1.3.2.1.jar)
>   MalisisSwitchesPlugin (malisisswitches-1.11.2-4.1.0.jar)
>   ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.11.jar)
>   TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
>   MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
> Contact their authors BEFORE contacting forge
> 
> // You're mean.
> 
> Time: 3/29/17 12:32 AM
> Description: Unexpected error
> 
> java.lang.NullPointerException: Unexpected error
> 	at net.minecraft.item.ItemTool.getHarvestLevel(ItemTool.java:129)
> 	at teamroots.embers.item.ItemClockworkAxe.canHarvestBlock(ItemClockworkAxe.java:100)
> 	at net.minecraft.item.ItemStack.func_150998_b(ItemStack.java:349)
> 	at net.minecraft.entity.player.InventoryPlayer.func_184432_b(InventoryPlayer.java:678)
> 	at net.minecraft.entity.player.EntityPlayer.func_184823_b(EntityPlayer.java:877)
> 	at net.minecraftforge.common.ForgeHooks.canHarvestBlock(ForgeHooks.java:174)
> 	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:203)
> 	at net.minecraft.block.Block.func_180647_a(Block.java:545)
> 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:408)
> 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:240)
> 	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1460)
> 	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2174)
> 	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
> 	at net.minecraft.client.main.Main.main(SourceFile:124)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at net.minecraft.item.ItemTool.getHarvestLevel(ItemTool.java:129)
> 	at teamroots.embers.item.ItemClockworkAxe.canHarvestBlock(ItemClockworkAxe.java:100)
> 	at net.minecraft.item.ItemStack.func_150998_b(ItemStack.java:349)
> 	at net.minecraft.entity.player.InventoryPlayer.func_184432_b(InventoryPlayer.java:678)
> 	at net.minecraft.entity.player.EntityPlayer.func_184823_b(EntityPlayer.java:877)
> 	at net.minecraftforge.common.ForgeHooks.canHarvestBlock(ForgeHooks.java:174)
> 	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:203)
> 	at net.minecraft.block.Block.func_180647_a(Block.java:545)
> 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:408)
> 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:240)
> 	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1460)
> 	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2174)
> 	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)
> 
> -- Affected level --
> Details:
> 	Level name: MpServer
> 	All players: 1 total; [EntityPlayerSP['Ayrrow'/332, l='MpServer', x=-487.90, y=65.00, z=564.57]]
> 	Chunk stats: MultiplayerChunkCache: 289, 289
> 	Level seed: 0
> 	Level generator: ID 06 - atg, ver 0. Features enabled: false
> 	Level generator options: 
> 	Level spawn location: World: (-12,64,244), Chunk: (at 4,4,4 in -1,15; contains blocks -16,0,240 to -1,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
> 	Level time: 1070705 game time, 1115730 day time
> 	Level dimension: 0
> 	Level storage version: 0x00000 - Unknown?
> 	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
> 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
> 	Forced entities: 9 total; [EntityButterfly['Glassy Tiger'/421, l='MpServer', x=-462.30, y=18.00, z=568.70], EntityButterfly['Holly Blue'/422, l='MpServer', x=-462.80, y=42.00, z=568.80], EntityButterfly['Brimstone'/423, l='MpServer', x=-461.61, y=58.00, z=567.75], EntityButterfly['Spicebush Swallowtail'/424, l='MpServer', x=-462.30, y=5.00, z=567.70], EntityPlayerSP['Ayrrow'/332, l='MpServer', x=-487.90, y=65.00, z=564.57], EntityButterfly['Canary Speckled Wood'/362, l='MpServer', x=-472.74, y=68.00, z=529.18], EntityButterfly['Citrus Swallowtail'/494, l='MpServer', x=-483.63, y=72.00, z=520.51], EntityButterfly['Citrus Swallowtail'/368, l='MpServer', x=-494.38, y=69.50, z=557.63], EntityBat['Bat'/2165, l='MpServer', x=-512.07, y=52.10, z=560.26]]
> 	Retry entities: 0 total; []
> 	Server brand: fml,forge
> 	Server type: Integrated singleplayer server
> Stacktrace:
> 	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
> 	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
> 	at net.minecraft.client.main.Main.main(SourceFile:124)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:483)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.11.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 1.8.0_25, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 628982376 bytes (599 MB) / 2402811904 bytes (2291 MB) up to 2796552192 bytes (2667 MB)
> 	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3000m -Xms256m -XX:PermSize=256m
> 	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
> 	FML: MCP 9.38 Powered by Forge 13.20.0.2260 94 mods loaded, 94 mods active
> 	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> 	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
> 	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
> 	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2260.jar) 
> 	UCHIJAAAA	forge{13.20.0.2260} [Minecraft Forge] (forge-1.11.2-13.20.0.2260.jar) 
> 	UCHIJAAAA	ivtoolkit{1.3.2.1} [IvToolkit] (minecraft.jar) 
> 	UCHIJAAAA	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
> 	UCHIJAAAA	forgeendertech{1.11.2-2.0.7.0} [Forge Endertech] (ForgeEndertech-1.11.2-2.0.7.0-build.0017.jar) 
> 	UCHIJAAAA	adchimneys{1.11.2-2.0.6.0} [Advanced Chimneys] (AdChimneys-1.11.2-2.0.6.0-build.0017.jar) 
> 	UCHIJAAAA	akashictome{1.1-7} [Akashic Tome] (AkashicTome-1.1-7.jar) 
> 	UCHIJAAAA	applecore{2.1.2} [AppleCore] (AppleCore-mc1.11.2-2.1.2.jar) 
> 	UCHIJAAAA	jei{4.2.10.250} [Just Enough Items] (jei_1.11.2-4.2.10.250.jar) 
> 	UCHIJAAAA	appleskin{1.0.6} [AppleSkin] (AppleSkin-mc1.11-1.0.6.jar) 
> 	UCHIJAAAA	astralsorcery{1.2.3-beta} [Astral Sorcery] (astralsorcery-1.2.3-beta.jar) 
> 	UCHIJAAAA	atg{2} [Alternate Terrain Generation] (atg-1.11.2-2.0.1.jar) 
> 	UCHIJAAAA	theoneprobe{1.4.5} [The One Probe] (theoneprobe-1.1x-1.4.5.jar) 
> 	UCHIJAAAA	attaineddrops{2.3.0} [Attained Drops 2] (AttainedDrops-1.11.2-2.3.0.jar) 
> 	UCHIJAAAA	morphtool{1.1-13} [Morph-o-Tool] (Morph-o-Tool-1.1-13.jar) 
> 	UCHIJAAAA	quark{r1.2-88} [Quark] (Quark-r1.2-88.jar) 
> 	UCHIJAAAA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
> 	UCHIJAAAA	bdlib{1.13.2.7} [BD Lib] (bdlib-1.13.2.7-mc1.11.2.jar) 
> 	UCHIJAAAA	betterwithmods{1.1.1} [Better With Mods] (Better With Mods-1.1.1-1.11.2.jar) 
> 	UCHIJAAAA	betterbuilderswands{0.11.1} [Better Builder's Wands] (BetterBuildersWands-1.11-0.11.1.239+9162f74.jar) 
> 	UCHIJAAAA	guideapi{1.11-2.1.0-51} [Guide-API] (Guide-API-1.11-2.1.0-51.jar) 
> 	UCHIJAAAA	bloodmagic{1.11-2.1.7-76} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.7-76.jar) 
> 	UCHIJAAAA	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
> 	UCHIJAAAA	chisel{MC1.11.2-0.0.9.11} [Chisel] (Chisel-MC1.11.2-0.0.9.11.jar) 
> 	UCHIJAAAA	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
> 	UCHIJAAAA	cookingforblockheads{5.3.13} [Cooking for Blockheads] (CookingForBlockheads_1.11.2-5.3.13.jar) 
> 	UCHIJAAAA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.11.2-3.0.24.jar) 
> 	UCHIJAAAA	crafttweaker{3.0.24} [Crafttweaker] (CraftTweaker-1.11.2-3.0.24.jar) 
> 	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.11.2-3.0.24.jar) 
> 	UCHIJAAAA	cxlibrary{1.4.0} [CXLibrary] (cxlibrary-1.11.2-1.4.0.jar) 
> 	UCHIJAAAA	storagedrawers{1.11.2-4.2.0} [Storage Drawers] (StorageDrawers-1.11.2-4.2.0.jar) 
> 	UCHIJAAAA	bitdrawers{0.4} [Drawers & Bits] (DrawersBits-1.11.2-0.4.jar) 
> 	UCHIJAAAA	earthworks{1.1.3} [Earthworks] (Earthworks-1.11.2-1.1.3.jar) 
> 	UCHIJAAAA	embers{0.206} [Embers] (embers-0.206.jar) 
> 	UCHIJAAAA	extrabitmanipulation{1.11.2-3.0.5} [Extra Bit Manipulation] (ExtraBitManipulation-1.11.2-3.0.5.jar) 
> 	UCHIJAAAA	felling{1.0} [Felling] (felling-1.0.jar) 
> 	UCHIJAAAA	flamingo{1.11-1.9} [Pink Flamingo] (Flamingo-1.11-1.9.jar) 
> 	UCHIJAAAA	flatcoloredblocks{mc1.11-5.1} [Flat Colored Blocks] (flatcoloredblocks-mc1.11-5.1.jar) 
> 	UCHIJAAAA	reborncore{2.13.5.42} [RebornCore] (RebornCore-1.11.2-2.13.5.42-universal.jar) 
> 	UCHIJAAAA	reborncore-mcmultipart{2.13.5.42} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.13.5.42-universal.jar) 
> 	UCHIJAAAA	fluxedredstone{@MODVERSION@} [FluxedRedstone] (FluxedRedstone-2.6.0.54.jar) 
> 	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (foamfix-0.6.2-beta2-anarchy.jar) 
> 	UCHIJAAAA	forestry{5.3.2.60} [Forestry] (forestry_1.11.2-5.3.2.60.jar) 
> 	UCHIJAAAA	forgelin{1.4.0} [Forgelin] (Forgelin-1.4.0.jar) 
> 	UCHIJAAAA	fw{1.5.0} [Fullscreen Windowed] (FullscreenWindowed-1.10.2-1.5.0.jar) 
> 	UCHIJAAAA	hammercore{1.4.3} [Hammer Core] (HammerCore_1.11.2-1.4.3.jar) 
> 	UCHIJAAAA	hcmw{1.0} [Homecraft Mineware] (hcmw-1.11.2-0.2.9-universal.jar) 
> 	UCHIJAAAA	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.11.2-0.11.0.jar) 
> 	UCHIJAAAA	jeibees{0.9.0.5} [JEI Bees] (jeibees-0.9.0.5-mc1.11.2.jar) 
> 	UCHIJAAAA	je_calculation{1.11.2-2.6.2} [Just Enough Calculation] (JustEnoughCalculation-1.11.2-2.6.2.jar) 
> 	UCHIJAAAA	loottweaker{0.0.5} [LootTweaker] (LootTweaker-1.11.2-0.0.5.jar) 
> 	UCHIJAAAA	jeresources{0.6.3.4} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.3.4.jar) 
> 	UCHIJAAAA	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.11.2.jar) 
> 	UCHIJAAAA	literalascension{1.11.2-1.0.1.1} [Literal Ascension] (literalascension-1.11.2-1.0.1.1.jar) 
> 	UCHIJAAAA	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
> 	UCHIJAAAA	malisiscore{1.11.2-5.1.1} [MalisisCore] (malisiscore-1.11.2-5.1.1.jar) 
> 	UCHIJAAAA	malisisdoors{1.11.2-6.1.0} [MalisisDoors] (malisisdoors-1.11.2-6.1.0.jar) 
> 	UCHIJAAAA	malisisswitches{1.11.2-4.1.0} [Malisis Switches] (malisisswitches-1.11.2-4.1.0.jar) 
> 	UCHIJAAAA	minemenu{1.5.0} [MineMenu] (MineMenu-1.11.2-1.5.0-universal.jar) 
> 	UCHIJAAAA	mtrm{1.2.1.22} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.11.2-1.2.1.22.jar) 
> 	UCHIJAAAA	morpheus{1.11.2-3.2.13} [Morpheus] (Morpheus-1.11.2-3.2.13.jar) 
> 	UCHIJAAAA	mtlib{@VERSION@} [MTLib] (MTLib-2.0.1.jar) 
> 	UCHIJAAAA	omlib{1.11.2-3.0.0-61} [OMLib] (omlib-1.11.2-3.0.0-61.jar) 
> 	UCHIJAAAA	ompd{3.0.0-21} [Open Modular Passive Defense] (ompd-1.10.2-3.0.0-21.jar) 
> 	UCHIJAAAA	openmodularturrets{1.10.2-3.0.0-100} [Open Modular Turrets] (openmodularturrets-1.10.2-3.0.0-100.jar) 
> 	UCHIJAAAA	harvestcraft{1.11.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2g.jar) 
> 	UCHIJAAAA	placeableitems{3.0.3.1} [Placeable Items Mod] (placeableitems-3.0.3.1.jar) 
> 	UCHIJAAAA	placementpreview{0.3.1} [Placement Preview] (placementpreview-1.11.0-0.3.1.jar) 
> 	UCHIJAAAA	shetiphiancore{3.4.3} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.3.jar) 
> 	UCHIJAAAA	platforms{1.3.3} [Platforms] (platforms-1.11.0-1.3.3.jar) 
> 	UCHIJAAAA	pressure{1.3.1.5} [Pressure Pipes] (pressure-1.3.1.5-mc1.11.2.jar) 
> 	UCHIJAAAA	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.11.2-1.2.3.jar) 
> 	UCHIJAAAA	reccomplex{1.2.10} [Recurrent Complex] (RecurrentComplex-1.2.10.jar) 
> 	UCHIJAAAA	rftools{5.90} [RFTools] (rftools-1.1x-5.90.jar) 
> 	UCHIJAAAA	rftoolscontrol{1.6.6} [RFTools Control] (rftoolsctrl-1.1x-1.6.6.jar) 
> 	UCHIJAAAA	rftoolsdim{4.55} [RFTools Dimensions] (rftoolsdim-1.1x-4.55.jar) 
> 	UCHIJAAAA	roots{0.014} [Roots 2] (roots-2-0.014.jar) 
> 	UCHIJAAAA	silentlib{2.0.5} [Silent Lib] (SilentLib-1.11.x-2.0.5-45.jar) 
> 	UCHIJAAAA	scalinghealth{1.0.5} [Scaling Health] (ScalingHealth-1.11.x-1.0.5-47.jar) 
> 	UCHIJAAAA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.11.jar) 
> 	UCHIJAAAA	spartanshields{1.2a} [Spartan Shields] (SpartanShields-1.11-1.2a.jar) 
> 	UCHIJAAAA	spiceoflife{1.3.8} [The Spice of Life] (SpiceOfLife-mc1.11.2-1.3.8.jar) 
> 	UCHIJAAAA	storageboats{1.6} [Storage Boats Mod] (StorageBoats-1.9.jar) 
> 	UCHIJAAAA	supercraftingframe{1.2.1.89} [Super Crafting Frame] (supercraftingframe-1.11-1.2.1.89.jar) 
> 	UCHIJAAAA	techreborn{2.1.10.88} [TechReborn] (TechReborn-1.11.2-2.1.10.88-universal.jar) 
> 	UCHIJAAAA	terraqueous{1.3.8} [Terraqueous] (terraqueous-1.11.0-1.3.8.jar) 
> 	UCHIJAAAA	tombmanygraves{1.11.2-3.0.1} [Tomb Many Graves] (TombManyGraves-1.11.2-3.0.1.jar) 
> 	UCHIJAAAA	toughasnails{@MOD_VERSION@} [Tough As Nails] (ToughAsNails-1.11-2.0.5.jar) 
> 	UCHIJAAAA	wearablebackpacks{2.3.0} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.3.0.jar) 
> 	UCHIJAAAA	weirdinggadget{1.0} [The Weirding Gadget] (weirdinggadget-1.11.2-0.1.7-universal.jar) 
> 	UCHIJAAAA	wolfarmor{1.3.2} [Wolf Armor and Storage] (wolfarmor-1.3.3.6.jar) 
> 	UCHIJAAAA	xnet{1.1.2} [XNet] (xnet-1.1.2.jar) 
> 	Loaded coremods (and transformers): 
> SHLoadingPlugin (ScalingHealth-1.11.x-1.0.5-47.jar)
>   net.silentchaos512.scalinghealth.asm.SHClassTransformer
> LoadingPlugin (Quark-r1.2-88.jar)
>   vazkii.quark.base.asm.ClassTransformer
> AppleCore (AppleCore-mc1.11.2-2.1.2.jar)
>   squeek.applecore.asm.TransformerModuleHandler
> ForgelinPlugin (Forgelin-1.4.0.jar)
>   
> RebornCoreASM (RebornCore-1.11.2-2.13.5.42-universal.jar)
>   reborncore.mixin.transformer.MixinTransformer
> DummyPlugin (ForgeEndertech-1.11.2-2.0.7.0-build.0017.jar)
>   
> CorePlugin (FluxedRedstone-2.6.0.54.jar)
>   
> CXLibraryCore (cxlibrary-1.11.2-1.4.0.jar)
>   cubex2.cxlibrary.CoreModTransformer
> llibrary (llibrary-1.7.4-1.11.2.jar)
>   net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
>   net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
> ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.3.jar)
>   shetiphian.core.asm.ClassTransformer
> Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.6.2-beta2-anarchy.jar)
>   pl.asie.foamfix.coremod.FoamFixTransformer
> literalascension (literalascension-1.11.2-1.0.1.1.jar)
>   com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
> IvToolkit (IvToolkit-1.3.2.1.jar)
>   
> MalisisSwitchesPlugin (malisisswitches-1.11.2-4.1.0.jar)
>   net.malisis.switches.asm.MalisisSwitchesTransformer
> ChiselCorePlugin (Chisel-MC1.11.2-0.0.9.11.jar)
>   team.chisel.common.asm.ChiselTransformer
> TANLoadingPlugin (ToughAsNails-1.11-2.0.5.jar)
>   toughasnails.asm.transformer.BlockCropsTransformer
>   toughasnails.asm.transformer.EntityRendererTransformer
>   toughasnails.asm.transformer.WorldTransformer
> MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
>   net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
>   net.malisis.core.util.chunkblock.ChunkBlockTransformer
>   net.malisis.core.renderer.transformer.MalisisRendererTransformer
>   net.malisis.core.renderer.icon.asm.TextureMapTransformer
>   net.malisis.core.util.clientnotif.ClientNotifTransformer
> 	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1151.1008' Renderer: 'AMD Radeon HD 6700M Series'
> 	List of loaded APIs: 
> 		* AppleCoreAPI (2.2.0) from AppleCore-mc1.11.2-2.1.2.jar
> 		* BetterWithModsAPI (Beta 0.6) from Better With Mods-1.1.1-1.11.2.jar
> 		* bloodmagic|API (1.11-2.1.7-76) from BloodMagic-1.11-2.1.7-76.jar
> 		* BotaniaAPI (79) from AkashicTome-1.1-7.jar
> 		* ChiselAPI (0.0.1) from Chisel-MC1.11.2-0.0.9.11.jar
> 		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.11.2-0.0.9.11.jar
> 		* ChiselsAndBitsAPI (13.8.0) from chiselsandbits-13.10.jar
> 		* CoFHAPI (1.8.9R1.2.0B1) from FluxedRedstone-2.6.0.54.jar
> 		* CoFHAPI|energy (1.8.9R1.2.0B1) from omlib-1.11.2-3.0.0-61.jar
> 		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.11.jar
> 		* compatlayer (0.2.5) from compatlayer-1.11.2-0.2.5.jar
> 		* ForestryAPI|apiculture (5.0.0) from forestry_1.11.2-5.3.2.60.jar
> 		* ForestryAPI|arboriculture (4.2.1) from forestry_1.11.2-5.3.2.60.jar
> 		* ForestryAPI|circuits (3.1.0) from forestry_1.11.2-5.3.2.60.jar
> 		* ForestryAPI|climate (2.1.0) from forestry_1.11.2-5.3.2.60.jar
> 		* ForestryAPI|core (5.1.0) from forestry_1.11.2-5.3.2.60.jar
> 		* ForestryAPI|farming (2.1.0) from forestry_1.11.2-5.3.2.60.jar
> 		* ForestryAPI|food (1.1.0) from forestry_1.11.2-5.3.2.60.jar
> 		* ForestryAPI|fuels (3.0.0) from forestry_1.11.2-5.3.2.60.jar
> 		* ForestryAPI|genetics (4.7.1) from forestry_1.11.2-5.3.2.60.jar
> 		* ForestryAPI|greenhouse (5.2.0) from forestry_1.11.2-5.3.2.60.jar
> 		* ForestryAPI|hives (4.1.0) from forestry_1.11.2-5.3.2.60.jar
> 		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.11.2-5.3.2.60.jar
> 		* ForestryAPI|mail (3.1.0) from forestry_1.11.2-5.3.2.60.jar
> 		* ForestryAPI|multiblock (3.0.0) from forestry_1.11.2-5.3.2.60.jar
> 		* ForestryAPI|recipes (5.4.0) from forestry_1.11.2-5.3.2.60.jar
> 		* ForestryAPI|storage (5.0.0) from forestry_1.11.2-5.3.2.60.jar
> 		* ForestryAPI|world (2.1.0) from forestry_1.11.2-5.3.2.60.jar
> 		* Guide-API|API (1.11-2.1.0-51) from Guide-API-1.11-2.1.0-51.jar
> 		* jeresources|API (0.6.3.4) from JustEnoughResources-1.11.2-0.6.3.4.jar
> 		* JustEnoughItemsAPI (4.11.0) from jei_1.11.2-4.2.10.250.jar
> 		* mcjtylib_ng (2.3.11) from mcjtylib-1.1x-2.3.11.jar
> 		* pressureAPI (1.3.1.5) from pressure-1.3.1.5-mc1.11.2.jar
> 		* reborncoreAPI (2.13.5.42) from RebornCore-1.11.2-2.13.5.42-universal.jar
> 		* reborncoreAPI|Fuel (2.13.5.42) from RebornCore-1.11.2-2.13.5.42-universal.jar
> 		* reborncoreAPI|Power (2.13.5.42) from RebornCore-1.11.2-2.13.5.42-universal.jar
> 		* reborncoreAPI|Recipe (2.13.5.42) from RebornCore-1.11.2-2.13.5.42-universal.jar
> 		* reborncoreAPI|Tile (2.13.5.42) from RebornCore-1.11.2-2.13.5.42-universal.jar
> 		* StorageDrawersAPI (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
> 		* StorageDrawersAPI|config (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
> 		* StorageDrawersAPI|event (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
> 		* StorageDrawersAPI|pack (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
> 		* StorageDrawersAPI|registry (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
> 		* StorageDrawersAPI|render (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
> 		* StorageDrawersAPI|storage (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
> 		* StorageDrawersAPI|storage-attribute (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.2.0.jar
> 		* techrebornAPI (2.1.10.88) from TechReborn-1.11.2-2.1.10.88-universal.jar
> 		* TerraqueousAPI (1.0) from terraqueous-1.11.0-1.3.8.jar
> 		* TerraqueousAPI|Cloud (1.0) from terraqueous-1.11.0-1.3.8.jar
> 		* TerraqueousAPI|Machines (1.0) from terraqueous-1.11.0-1.3.8.jar
> 		* TerraqueousAPI|Plant (1.0) from terraqueous-1.11.0-1.3.8.jar
> 		* theoneprobe_api (1.4.4) from theoneprobe-1.1x-1.4.5.jar
> 	RebornCore: 
> 		Plugin Engine: 0
> 		RebornCore Version: 2.13.5.42
> 		Mixin Status: 1
> 		Runtime Debofucsation 1
> 		RenderEngine: 0
> 	Launched Version: forge-13.20.0.2260
> 	LWJGL: 2.9.4
> 	OpenGL: AMD Radeon HD 6700M Series GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
> 	GL Caps: Using GL 1.3 multitexturing.
> Using GL 1.3 texture combiners.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Shaders are available because OpenGL 2.1 is supported.
> VBOs are available because OpenGL 1.5 is supported.
> 
> 	Using VBOs: No
> 	Is Modded: Definitely; Client brand changed to 'fml,forge'
> 	Type: Client (map_client.txt)
> 	Resource Packs: 
> 	Current Language: English (US)
> 	Profiler Position: N/A (disabled)
> 	CPU: 4x Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz 

And full log - https://pastebin.com/8eK7Vdqf

**Comment by Ayrrow** [comment]
Seems to relate to #145

**Comment by GeekBeam** [comment]
It is exactly the same issue as #145 , which is a continuation of the bugs that weren't solved in #133 by the 0.206 update. the clockwork pick is currently the _only_ truly safe tool to use. any instance where it doesn't mine as a pickaxe where a normal one should, remember to steer clear of with your axe. this includes all chisel, and quark blocks, hoppers, furnaces, and others.

a useful predictive measure is to use *The One Probe* and enable it always, and keep an eye on the harvest level, it will read out a "default error" text in red when you are going to crash.

**Comment by Ayrrow** [comment]
thanks
