### ISSUE TITLE
Item Pipes don't respect results of IItemHandler

### ISSUE THREAD

**Issue by dmillerw** [RootsTeam/Embers#156]
Item Pipes try to insert into a lot based on the stack-size and max stack size of the Item currently in said slot. It will keep trying to insert into said slot even if the IItemHandler reports that the slot is full

Currently an issue with the latest version of Embers for 1.10 and 1.11

**Comment by elucent** [comment]
Fixed in my dev environment. I will fix this in 1.11 soon.
