### ISSUE TITLE
[1.11.2 - 0.206] rendering crash due to particle rendering.

### ISSUE THREAD

**Issue by GeekBeam** [RootsTeam/Embers#157]
was using a bin/block breaker pair with flowing lava. block breaker breaks flowing lava, and has no result to render(?) not sure if that's what caused the crash, as it broke the flowing lava several times before the crash ocurred.

[[LOG]](http://puu.sh/v6WWd/f2ef464843.txt)

**Comment by elucent** [comment]
Added a new nullcheck that should fix this. Will be in the next release.
