### ISSUE TITLE
Atmospheric Gauge is bugged on depleted chunks.

### ISSUE THREAD

**Issue by InflamedSebi** [RootsTeam/Embers#159]
The ember is limited per chunk and can deplete, right?

How it should behave:
The Atmospheric Gauge shows how much ember can still be mined with the bore. As soon as the Chunk is depleted, the Atmospheric Gauge will stay at the far left to represent it's an empty chunk.

How it actually behaves:
The Atmospheric Gauge shows how much ember can still be mined with the bore. As soon as the Chunk is depleted, the Atmospheric Gauge shows the initial amount of ember of this chunk.  So its not possible to tell, if a chunk is completely empty or just untouched. The bore will not mine in an empty chunk as expected, but it's kinda annoying to first place the bore to check if this chunk is suitable.

Pack is FTB Beyond 1.2.1 and i tried in Aroma's Mining-Dimension.
Ember version: 0.104

**Comment by elucent** [comment]
Embers in 1.10.2 is buggy as all heck, and I haven't supported it in about four months. You could try a 1.11.2 pack if you want to try Embers as it should be, or you can stay on 1.10.2 on an effectively broken version of the mod. I don't expect you to update for just one mod, but that's your situation as far as Embers is concerned.

**Comment by InflamedSebi** [comment]
Well, there aren't any FTB packs for 1.11 yet, so I'll stay with the buggy version then. Ty for reply.

**Comment by elucent** [comment]
Closing this because I am not supporting 1.10.2 anymore.
