### ISSUE TITLE
[1.11.2 - 0.206] Dawnstone Anvil item dupe bug

### ISSUE THREAD

**Issue by dracojames** [RootsTeam/Embers#163]
I noticed this first in the Raxpack 2 modpack, but also created a separate 1.11.2 profile with only Embers installed and the same bug is still present.

Hold an item, then either place (if a placeable item/block) or drop the item, leaving you with an empty hand, then right click the anvil. Whatever item you were holding will appear on the anvil as if place there. The item can then be removed from the anvil and used, leaving the original item where you placed or dropped it.

Simplest way to see this is hold a Dawnstone Anvil item in your hand, place it in the world and right click the anvil with your empty hand, which will duplicate the anvil you just placed. Seems to be infinitely repeatable.

**Comment by elucent** [comment]
Should be fixed.
