### ISSUE TITLE
Improved item naming conventions

### ISSUE THREAD

**Issue by RetroRodent** [RootsTeam/Embers#164]
I have a few suggestions for making the names of items more consistent, this would make it easier to find and identify related items in JEI and searchable inventories:

Item pipe devices have a good naming convention:
- Item Pipe
- Item Pump
- Item Vacuum
- Item Dropper
- Item Transfer
- Bin

"Item Bin" could be an improvement because "bin" turns up a lot of results in a search but overall these are great.

Fluid pipes not so much:
- Iron Pipe
- Mechanical Pump
- Fluid Vessel
- Reservoir
- Caminite Ring

The words iron and item also look really similar.

Suggested names:
- Fluid Pipe
- Fluid Pump
- Fluid Vessel
- Fluid Reservoir
- Reservoir Expansion

"Fluid reservoir" does seems a bit redundant but still, it'd show up with the rest in a search.
IMO it's less important to have fluid in the name of the caminite ring, but giving it some relation to the reservoir indicates its purpose and differentiates it from the caminite building/crafting materials.

IO port upgrades:
- Mechanical Core
- Machine Accessor

Suggestions:
- Mechanical Core
- Mechanical Accessor

Thanks for the excellent mod, really looking forward to seeing where it goes with the new materials and alchemy.

**Comment by elucent** [comment]
I've considered this but I like them as they are. Inconsistencies lend character.
