### ISSUE TITLE
Item Pipes and Mekanism

### ISSUE THREAD

**Issue by fallenhunter1** [RootsTeam/Embers#167]
Appears that these two mods don't work well together.

Item pipes will not connect to the Mek machines. If you think its a Mek Issue, will report it there.

Trying to pipe from a chest to a sawmill, item pipe will not connect. I have set the input side before and after attempt, and still no result.

Latest version in release, for both mods. On a server, if that matters,

**Comment by elucent** [comment]
Probably a Mek issue, but I'm not updating Embers in 1.10.2 any more.
