### ISSUE TITLE
[1.11.2 - 0.207] Chat line rendering bug (causes server crash? not sure)

### ISSUE THREAD

**Issue by GeekBeam** [RootsTeam/Embers#169]
seems to be that Embers is attempting to put a chat line when holding a "Heat enabled item" onto the chat bar, which seems to be crashing my client, _and_ the server I am playing upon.

[[log](https://puu.sh/vwX76/36554123fd.txt)]

**Comment by elucent** [comment]
Yes, fixed in 0.208.
