### ISSUE TITLE
Inferno Forge Dupe on Break

### ISSUE THREAD

**Issue by Lendysawk** [RootsTeam/Embers#170]
It appears that the hatch part of the multiblock is sometimes counting as a separate inferno forge, and dropping another block when broken.

Embers v0.209

**Comment by elucent** [comment]
Any idea specifically when?

**Comment by Lendysawk** [comment]
I was able to replicate it several times, but not every time. It seemed to happen most often when mining the machine from the center on the bottom, or from the hatch itself, with the clockwork pickaxe. 
Because of the numerous issues with the clockwork tools, it may in fact be the pick's fault, I'm not sure.
Once when I placed the forge itself, it had two hatches, one floating one block above the connected one. It may also just be an issue of creating 2 hatches on placement. One open and one closed maybe?

**Comment by Lendysawk** [comment]
Side note suggestion:
Honestly, there seems to have been several issues with machines that take up multiple block spaces. 
Would it not be simpler, and possibly more complex to craft (for the better) these multiblock machines block by block, taking an approach similar to Immersive Engineering? One would build specific types of blocks then place them in a configuration, utilizing your machine cores and accessors, to actually create these multiblock machines. They would then be hit by a tinker's hammer to complete the multiblock. They would retain the ability to be expanded upon post creation with more cores and accessors.

When breaking one part of the multiblock, it would revert it back to the separate blocks that created it, and only drop that specific block that was mined, instead of trying to remove and drop the whole machine.

**Comment by elucent** [comment]
Making those kinds of multiblocks is way more convoluted and also means I'd have to make a lot of component blocks to make those multiblocks. It'd also make the multiblocks way way more expensive if I wanted to make them have any kind of sane recipes. I'm not a fan.

Regardless, I'll fix the dupe for the next update.
