### ISSUE TITLE
[Suggestion] Fortune + Superheating Modifier Mining

### ISSUE THREAD

**Issue by Lendysawk** [RootsTeam/Embers#171]
HIgher levels of both Fortune Enchantment plus Superheating Modifier results in a chance for automatic ore doubling of smeltable ores such as iron. (ores may drop multiple ingots, tree blocks could drop multiple pieces of charcoal)

Testing has not yielded this expected result.

**Comment by elucent** [comment]
This is intentional. Otherwise you could easily cheat ore multiplication.
