### ISSUE TITLE
[1.11.2 - 0.210] swinging a weapon with Casting on it ridiculously fast nets a server crash.

### ISSUE THREAD

**Issue by GeekBeam** [RootsTeam/Embers#172]
applying the Casting ability to a weapon or any tool will give you a chance for the casting perk to proc every swing, and guaranteed to proc when swinging for a critical hit.

swinging a weapon fast enough, I was able to crash a server, and upon further testing with an "embers only" server, the same crash occured.

the log is INCREDIBLY unspecific as to what happens, but both crashes, I was wildly swinging the weapon around trying to hit enemies at range.

[[log](https://pastebin.com/1R7anscn)] courtesy of Lordi91, whom setup the remote server to test this bug upon.

**Comment by GeekBeam** [comment]
upon further testing, this crash can occur with ANY given swing of tool/weapon with Ember Casting upon it. (the tools this was tested upon were the Clockwork pick, and Blood Magic's Sentient Sword.

**Comment by elucent** [comment]
Added a minimum cooldown of one second.
