### ISSUE TITLE
[1.11.2 - 0.206] cascading worldgen lag crash

### ISSUE THREAD

**Issue by Boodaflow** [RootsTeam/Embers#174]
After starting  up a new world, I started exploring near the spawn point until a sudden crash.
This issue seems to involve several mods including: Embers, Inventory Pets, AbyssalCraft, Recurrent Complex, Astral Sorcery, denseores, and Roguelike Dungeons.

Using Forge-13.20.0.2282
[15:09:07] [Server thread/WARN]: Embers loaded a new chunk (-21, 8  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.

I tried posting the log in zip, but it wouldn't upload.

**Comment by Boodaflow** [comment]
capnkirok of Inventory-Pets seems to have the solution:

https://github.com/capnkirok/Inventory-Pets/issues/170

**Comment by elucent** [comment]
This is not a crash from worldgen lag, nor is your crash my fault. It'll probably slow your world generation a _tiny bit_, but not much overall. Regardless, I'll try and make the lag even _more_ insignificant in the next release.
