### ISSUE TITLE
Disabling compat items corruptes oreDict

### ISSUE THREAD

**Issue by tyra314** [RootsTeam/Embers#175]
When you disable some/all of  the compat item, blocks and recipes, it causes some other mods to crash, when accessing OreDictionary.getOreIDs.

Affected mods:
Charcoal Pit
GravelOres

Versions:
forge-1.11.2-13.20.0.2285
embers-0.210

Example Crashlog:
https://gist.github.com/tyra314/46de7596dad5185d37a6fce835de96cd

*edit: I guess the error comes from this [lines](https://github.com/RootsTeam/Embers/blob/master/src/main/java/teamroots/embers/recipe/RecipeRegistry.java#L907). They should be also guarded with `if(ConfigManager.enableTin)` and such.

**Comment by elucent** [comment]
Sorry, silly mistake, will be fixed for the next release.
