### ISSUE TITLE
[Embers 0.210] Bronze mixing recipe wrong

### ISSUE THREAD

**Issue by cake-master** [RootsTeam/Embers#177]
Embers Version: 0.210
Minecraft Version: 1.11.2
Forge Version: 13.20.0.2285

Looking in JEI and through the source code, the recipe for molten bronze in a mixer should be: 2mb tin + 6mb copper = 8mb bronze.
However, through testing in creative I've found that 2000mb tin + 6000mb copper = 2672mb bronze.
This was tested further using an instance of Minecraft containing only Forge and Embers, which yielded the same result.
I couldn't find the source of the issue by looking at the source code.

**Comment by GeekBeam** [comment]
how are you getting the 2Kmb and 4Kmb of copper and tin? if you used the melter, you should receive 144mb per ingot, and twice that for a piece of ore.

**Comment by cake-master** [comment]
I filled 2 separate fluid vessels, one with 2000mb tin and one with 6000mb copper. I then pumped each into a mixer, so I could get exact results.
This was done after noticing a problem in the recipe in survival using ingots.

**Comment by GeekBeam** [comment]
try using smaller amounts of these metals, you may be hitting the upper bounds of the output buffer for the Mixer.

**Comment by cake-master** [comment]
The output buffer of the mixer is 8000mb, and as I've said I first noticed that the recipe wasn't accurate when using ingots.

**Comment by elucent** [comment]
Fixed for next release.
