### ISSUE TITLE
[0.009] Frame rate drop when Embers machines are running

### ISSUE THREAD

**Issue by Alsender** [RootsTeam/Embers#18]
Forge Version: 12.18.2.2099
Operating System: Linux (amd64) version 4.4.0-36-generic
Java Version: 1.8.0_91 64bit

I can usually get between 50 and 40 fps on the surface, and 60 at bedrock.  I do not suffer any frame rate drop when machines are set up, just sitting there, but once I turn them on, I drop to about 20 fps, at both surface and bedrock.  It does not have to be a lot of machines either.  Only one has to be running for me to suffer this frame rate drop.  Changing the particles settings does not effect my frame rate either.  Even from a good distance, my frame rate drops when I look in their general direction.

![2016-10-13_18 33 39](https://cloud.githubusercontent.com/assets/16634735/19370610/ca2f80d2-917a-11e6-8070-66464599e515.png)
Standing at bedrock, no ember bore. 60 fps

![2016-10-13_18 35 24](https://cloud.githubusercontent.com/assets/16634735/19370632/ea95f1c6-917a-11e6-8bfe-3d1b870a55da.png)
Standing at bedrock, ember bore OFF. 59 fps

![2016-10-13_18 36 07](https://cloud.githubusercontent.com/assets/16634735/19370644/f9353a0c-917a-11e6-827f-cdc123ad4bb5.png)
Standing at bedrock, ember bore ON. 19 fps

![2016-10-13_18 46 56](https://cloud.githubusercontent.com/assets/16634735/19370655/0cf042c6-917b-11e6-902c-c616a1aa29bc.png)
Surface, no embers machines. 48 fps

![2016-10-13_18 59 57](https://cloud.githubusercontent.com/assets/16634735/19370667/248e91f8-917b-11e6-9173-070e4cb10697.png)
Surface, ALL embers machines ON. 14 fps

![2016-10-13_19 13 56](https://cloud.githubusercontent.com/assets/16634735/19370681/3524b2a4-917b-11e6-81b2-c878fbccdb9d.png)
Surface, ALL embers machines OFF. 48 fps

![2016-10-13_19 19 27](https://cloud.githubusercontent.com/assets/16634735/19370687/3ff74ab6-917b-11e6-88b0-2f703bbda91b.png)
Surface, copper coil ONLY ON. 17 fps

![2016-10-13_19 19 47](https://cloud.githubusercontent.com/assets/16634735/19370694/4cfa23be-917b-11e6-973a-9eb679cda486.png)
Surface, copper coil ONLY ON, DECREASED PARTICLES. 19 fps

**Comment by elucent** [comment]
I have some optimizing to do, that's a lot of block updates.

**Comment by Alsender** [comment]
Guess you released it in alpha for a reason though, right?

**Comment by elucent** [comment]
Yeah, definitely. It's my first time doing this kind of expandable tech-style mod, there's bound to be some issues like this.

**Comment by elucent** [comment]
I think it's been mostly fixed up at this point, but tell me how it works for you. I cut out a lot of notifyBlockUpdate calls, but I'm still sending a lot of packets to synchronize the data. I'll be releasing a build on CurseForge shortly, let me know if it improves your performance so I can close this issue!

**Comment by Alsender** [comment]
Oh wow, I wasn't expecting such an immediate fix! I'll be sure to check it out as soon as I can!

**Comment by Alsender** [comment]
That did the trick.
