### ISSUE TITLE
[1.11.2 - 0.210] Embers ores aren't spawning in Aroma Mining Dimension.

### ISSUE THREAD

**Issue by billybricker** [RootsTeam/Embers#180]
Just as the title states Embers ores aren't spawning in Aroma's mining dimension. I found a [similar bug report](https://bitbucket.org/Aroma1997/miningworld/issues/83/some-mod-ores-missing) on Aroma's tracker that suggests that the issue was fixed by the mod authors whose blocks weren't generating. Would this be something you'd be willing to look into or should I look into another mod for ore generation for this pack?

**Comment by elucent** [comment]
Will be fixed in the next release.
