### ISSUE TITLE
Embers 0.210 MC 1.11.2 Clockwork Pickaxe crashes game

### ISSUE THREAD

**Issue by Ricin83** [RootsTeam/Embers#182]
Im running Embers 0.210 on Mc 1.11.2, and whenever I attempt to mine certain blocks, I get an instant crash to desktop. The blocks I've found to cause this so far are Slate, from the [Rustic](https://minecraft.curseforge.com/projects/rustic) mod, as well as vanilla Minecraft blocks such as Nether Bricks, Cobblestone Stairs, Redstone Blocks, Webs, and Hoppers. I suspect it has something to do with determining what to drop when mined, because it only happens in Survival, and the Grandhammer doesn't cause this either. The game gives me this error when I crash:

The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error

**Comment by Leviathan143** [comment]
Please provide the full crash report. A single line is useless.

**Comment by Ricin83** [comment]
Ahh, my bad.  Here it is:

[crash-2017-05-09_10.30.00-client.txt](https://github.com/RootsTeam/Embers/files/987465/crash-2017-05-09_10.30.00-client.txt)

**Comment by elucent** [comment]
Will fix in next build.
