### ISSUE TITLE
1.11.2 Embers.212 Clockwork Pickaxe, GrandHammer, and Battleaxe right-click doesn't work

### ISSUE THREAD

**Issue by poboy975** [RootsTeam/Embers#183]
Just what the title says, I've been playing the primal world technicians pack, single player survival. and I've built the clockwork tools, but the pickaxe, battleaxe and grandhammer secondary abilities don't do anything. The Cinderstaff works, as does the beam cannon. I do have a fully charged jar and cartridge, with the cartridge in the off-hand slot.

**Comment by Leviathan143** [comment]
I believe the secondary abilities were moved to augments in 1.11.2 Embers.

**Comment by poboy975** [comment]
Ok, you're right, I didn't have a codex so didn't see the changes about the heat and upgrading.
