### ISSUE TITLE
Colon in EmberWorldData breaks on Windows

### ISSUE THREAD

**Issue by Kezz101** [RootsTeam/Embers#184]
[This](https://github.com/RootsTeam/Embers/blob/master/src/main/java/teamroots/embers/world/EmberWorldData.java#L24) line of code in the `EmberWorldData` class adds a colon to the name of the `dat` file that Forge creates. Windows doesn't support colons in file names so Java can be a bit funky when you try to do this. In certain versions of Java, everything after the colon is stripped away from the file that is created and this causes weird issues when loading/saving data to/from the file. This would also break when you move a world between Windows and Linux systems.

I think this should be changed to an underscore or something. Alternatively, just use the `modid` seeing as you don't use any other data files. I'll attach a PR with this issue that simply changes this, however, this isn't ideal as it won't copy data over from previous dat files.

**Comment by Kezz101** [comment]
Also, this was the reason the old `/ember-fill` command was a bit temperamental on Windows. As it could never find the NBT entry in the file (as the file didn't exist!).

**Comment by elucent** [comment]
I'll have this fixed in the next release!
