### ISSUE TITLE
[1.11.2] Wrong recipe for Caminite Brick Stairs

### ISSUE THREAD

**Issue by 016Nojr** [RootsTeam/Embers#186]
The Caminite Brick Stairs has 2 crafting recipes, one of them is 6 Caminite Bricks. The other (Is atleast shown as 6x6 Caminite Brick Slabs in JEI)

https://gyazo.com/fa4433cb41a2b3bcd964ae21dee879d7

Forge: 2298
Embers: 0.210
JEI: 4.3.3.270

**Comment by 016Nojr** [comment]
Actually, this might be JEI's fault. @mezz

**Comment by mezz** [comment]
I just draw the recipes given to JEI, not create them.

**Comment by 016Nojr** [comment]
I took a look at some Botania slab recipes and it's the same case there, shows as 6 instead of 1

**Comment by elucent** [comment]
This is the fault of whichever mod is adding that slabs recipe most likely. Nothing I or mezz have done should cause this.

**Comment by 016Nojr** [comment]
So you dont add that slab recipe? Interesting...

**Comment by 016Nojr** [comment]
And of course it seems like Quark is doing it...
