### ISSUE TITLE
[1.11.2 - 0.213] Ancient Golem Crash

### ISSUE THREAD

**Issue by colejagdtiger** [RootsTeam/Embers#188]
In the latest version of embers whenever an ancient golem hits a player with a projectile the game crashes.

**Comment by colejagdtiger** [comment]
Here is the crash report
[crash-2017-05-26_13.26.06-server.txt](https://github.com/RootsTeam/Embers/files/1032830/crash-2017-05-26_13.26.06-server.txt)

**Comment by elucent** [comment]
Oh, whoops! Sorry, I have Baubles in my dev environment, and apparently my IDE imported the wrong PacketHandler class!

I'll get that fixed right away!

**Comment by elucent** [comment]
Will be fixed in the next release, which I am uploading to CurseForge now!
