### ISSUE TITLE
1.11.2 Config Request

### ISSUE THREAD

**Issue by MrSapient** [RootsTeam/Embers#190]
I want to be able to control the ore spawning by a different mod however there is no option to turn off ore spawning for Copper, Lead, Silver .. So my request is a config option to turn off ore spawning of these ores.

**Comment by elucent** [comment]
Just set vein count to zero?

**Comment by MrSapient** [comment]
So no chance of getting a copper , lead , silver config option to just turn them off ?

**Comment by elucent** [comment]
I don't see much point. I don't have that for any other ores.

**Comment by MrSapient** [comment]
https://pastebin.com/uwsr8s2n

You do under compatibility with other mods. section at the top...

**Comment by elucent** [comment]
Yes, but that's because the ore isn't even being registered. enableAluminum toggles the registration of _all aluminum items_. Not just oregen. Which is why the setting is there and I don't just assume people will know to set vein count to zero.
