### ISSUE TITLE
[1.11.2 - 0.214] Dial vs Gauge (wording - minor)

### ISSUE THREAD

**Issue by VallenFrostweaver** [RootsTeam/Embers#192]
In the Ancient Codex guages are called dials on the icon and in the description. In JEI and when hovered over in your inventory they are called gauges. This can be very confusing for someone new to Embers.
![dials v gauges](https://cloud.githubusercontent.com/assets/13642054/26677983/2992ade6-46c6-11e7-8721-071231caf6e2.png)

**Comment by elucent** [comment]
Updated to use "dials" reliably.
