### ISSUE TITLE
[1.10.2] [Question] Allowing other mods to utilize ember?

### ISSUE THREAD

**Issue by sipes42** [RootsTeam/Embers#193]
I am currently working on a mod pack, and I am trying to add as much crossover between the mods as possible. I am trying to figure out out how to allow a block to use and store ember, and also how to allow the hammer to designate the block as a receptor. If you are able to help in any way, or direct me to  good place to look in the API, that would be fantastic!

**Comment by teldon** [comment]
As far as I know 1.10.x version isn't being updated anymore.

**Comment by SirWindfield** [comment]
I had exactly the same thought. Adding new recipes to the altar would be cool ^_^
I am currently crafting some survival/tech mod that has a lot of crossover between the mods @sipes42 . But the twist is more like the ftb kappa mode. Making it quite hard to get stuff :P

**Comment by elucent** [comment]
For a block that stores ember: https://github.com/RootsTeam/Embers/blob/master/src/main/java/teamroots/embers/tileentity/TileEntityCopperCell.java

For a block that uses ember, the exact implementation varies depending on what you want to do. Just make a block with ember storage and remove the ember if certain conditions are met. Examples:
https://github.com/RootsTeam/Embers/blob/master/src/main/java/teamroots/embers/tileentity/TileEntityHeatCoil.java
https://github.com/RootsTeam/Embers/blob/master/src/main/java/teamroots/embers/tileentity/TileEntityFurnaceBottom.java
https://github.com/RootsTeam/Embers/blob/master/src/main/java/teamroots/embers/tileentity/TileEntityMixerBottom.java

For making something a valid emitter destination, simply implement IEmberPacketReceiver and you should be good to go. Example:
https://github.com/RootsTeam/Embers/blob/master/src/main/java/teamroots/embers/tileentity/TileEntityReceiver.java
