### ISSUE TITLE
[Bug] Right clicking on full fluid vessel with full bucket causes fluid to be placed.

### ISSUE THREAD

**Issue by VariablePwn** [RootsTeam/Embers#194]
If the fluid vessel is at maximum capacity (eg with water, lava) and is subsequently right clicked on with a bucket of same liquid, the bucket will be emptied and it's contents placed in the world. This can cause issues such as water flow, or lava damage.

**Comment by elucent** [comment]
This is the case with most tanks from most mods. I'm going to leave it this way. Just be careful!
