### ISSUE TITLE
[1.11.2 - 0.214] Item dupe with Dawnstone Anvil

### ISSUE THREAD

**Issue by Efimero** [RootsTeam/Embers#195]
While applying upgrades to a Clockwork Pickaxe on the Dawnstone Anvil, I picked up the upgraded pick and maybe placed it again on the anvil, but in the end I got two copies of the level 4 pick with 4 upgrades.
Placing both in the anvil again they got deconstructed properly as two different picks, so it was definitely a dupe, not a visual desync.

**Comment by elucent** [comment]
I believe this should be fixed.
