### ISSUE TITLE
[1.11.2 - 0.214] Clockwork pick doesn't drop bricks

### ISSUE THREAD

**Issue by Efimero** [RootsTeam/Embers#198]
Mining everything else seems fine and mining stone bricks with other picks works normally, but when mining a stone brick block with the clockwork pickaxe it takes longer and the brick just poofs and doesn't drop.

**Comment by Geird** [comment]
To add to this, the same seems to apply to Chisel marble/limestone, and the blood infuser from Evilcraft.

**Comment by elucent** [comment]
Will be fixed in the next build. Harvest levels are hard! :P
