### ISSUE TITLE
build.gradle is damaged

### ISSUE THREAD

**Issue by Reoseah** [RootsTeam/Embers#20]
Have just downloaded repository from GitHub. Gradle fails on any command.
See 23-27 lines of build.gradle:
```
<<<<<<< HEAD
version = "0.010"
=======
version = "0.007"
>>>>>>> 70cb7d1a4ebb3a05f19bfe0ae3b7fc9b7c7b984c
```

Log:
```
C:\Users\Meonemeou\Documents\GitHub\Embers>gradle setupDecompWorkspace
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\Meonemeou\Documents\GitHub\Embers\build.gradle' line: 23

* What went wrong:
Could not compile build file 'C:\Users\Meonemeou\Documents\GitHub\Embers\build.g
radle'.
> startup failed:
  build file 'C:\Users\Meonemeou\Documents\GitHub\Embers\build.gradle': 23: unex
pected token: << @ line 23, column 1.
     <<<<<<< HEAD
     ^

  1 error


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 24.898 secs
```

**Comment by Reoseah** [comment]
After removing that things added by some repository-management tool, calling `setupDecompWorkspace` and importing it into eclipse, eclipse has this errors:
```
Description	Resource	Path	Location	Type
Project 'Embers' is missing required library: 'C:\Users\Meonemeou\Documents\GitHub\Embers\libs'	Embers		Build path	Build Path Problem

Description	Resource	Path	Location	Type
The project cannot be built until build path errors are resolved	Embers		Unknown	Java Problem
```
It's quite obvious problem... If I remember correctly instead of this:
```
compile files('libs/')
```
should be this:
```
compile fileTree(dir: 'libs', include: '*.jar')
```

**Comment by Reoseah** [comment]
Changing that line in build script seems to work, but as there is no libraries in that /libs folder, now eclipse generates errors for missing imports "minetweaker" and "stanhebben".

Also eclipse has more then a thousand of warnings, mostly for unused imports...

**Comment by Reoseah** [comment]
Oh, and this repository has no .gitignore file...

**Comment by Reoseah** [comment]
So, I have fixed all this issues to just show this: Reoseah@9a957eb52ce39dc993b06c62ebdc7e52362ae449

I can make pull request with also all of the things described earlier, if possible..

**Comment by elucent** [comment]
My build.gradle and libs folder are fixed in my setup, I just need to push them. As for the warnings in eclipse, I just haven't gotten around to fixing those.

**Comment by elucent** [comment]
This'll be fixed once I push.
