### ISSUE TITLE
[1.11.2] add call for hasCapability

### ISSUE THREAD

**Issue by Terpo** [RootsTeam/Embers#203]
This line a creating an NPE in my mod:

https://github.com/RootsTeam/Embers/blob/master/src/main/java/teamroots/embers/tileentity/TileEntityPump.java#L250

There is no call for hasCapability but I am implementing my safety checks in hasCapability as it shouldn't be needed in getCapability

here is my code: 
https://github.com/Terpo/Waterworks/blob/master/src/main/java/org/terpo/waterworks/tileentity/TileEntityRainCollector.java#L85

and my crash log:
https://gist.github.com/Terpo/6e659e5fbb6cf2382b16d433efe2090b

I tried to follow the forge docs as capabilities are called quite often:

> It is strongly suggested that direct checks in code are used to test for capabilities instead of attempting to rely on maps other other data structures, since capability tests can be done by many objects every tick, and they need to be as fast as possible in order to avoid slowing down the game.

**Comment by elucent** [comment]
Added checks to this class and other similar classes. My bad, sorry!

**Comment by Terpo** [comment]
Well, you added some checks but in my case they do not get called ^^
I built a build from your current source and added it directly to my dev env. After creating two breakpoints: one for hasCapability and one for getCapability only the latest one is called.

Fun fact... when a add the safety checks to getCapability I can continue and after THAT hasCapability is called.

I know that I am on the latest source as my build of your code got the version 215

Also... I think your pipe rendering broke after the update http://imgur.com/maxOQYM
(after a relog its working)
