### ISSUE TITLE
Clockwork Pickaxe not mining ores

### ISSUE THREAD

**Issue by Dryeyes** [RootsTeam/Embers#207]
MC - 1.11.2
Forge - 13.20.0.2310
Embers - 0.214
Mekanism - 9.3.1

Firstly I just wanted to say, really love this mod so please keep up the good work. I'm currently playing around with the mod for the first time in survival mode. I'm trying to use this as my primary tech mod as I love anything dwarven, this mod is fitting to my style very nicely. 

I have other tech mods installed, Mekanism, which also as ore gen. It appears that anything other then Vanilla MC/Embers ore gen cannot be mined with this pickaxe, just breaks the block. This is forcing me to revert back to vanilla picks, which is frustrating as I really getting into this mod. 

I have The One Probe mod install and this show a red cross, suggesting in not compatible with Mekanism ores. Not sure if its the same with other mods that have ore gen as I just building up a mod pack of my own. 

Sorry if this as already been answered, I did look before posting and I couldn't see another post about it. 

Is this behavior correct, intended or is this a bug as I would like to be able to mine everything with this Clockwork Pickaxe?

Appreciate your time.

Dryeyes

**Comment by elucent** [comment]
Will be fixed when I release the next build.
