### ISSUE TITLE
[1.11.2] Crash on server load

### ISSUE THREAD

**Issue by EmosewaGamer** [RootsTeam/Embers#208]
So, whenever someone loads a world on a server with version 2.015, it crashes. By what I can gather from the log, it has to do with the Small Ruins. The crazy things is that they're set to 0/disabled.

Encountered an unexpected exceptionjava.lang.IllegalArgumentException: bound must be positive    at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_102]    at teamroots.embers.world.WorldGenSmallRuin.generate(WorldGenSmallRuin.java:116) ~[WorldGenSmallRuin.class:?]    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:172) ~[GameRegistry.class:?]    at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1002) ~[auo.class:?]    at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:982) ~[auo.class:?]    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:158) ~[lv.class:?]    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:302) ~[MinecraftServer.class:?]    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:272) ~[MinecraftServer.class:?]    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:267) ~[lh.class:?]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:442) [MinecraftServer.class:?]    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_102]

**Comment by elucent** [comment]
Setting them to zero does not disable them. The chance for the small ruins to spawn is 1/<config chance>. By setting it to zero, you're giving them an infinite chance to spawn and the game crashes.

I'll add the functionality of disabling when set to zero in the future, but for now, I'd recommend changing away from setting them to zero.

**Comment by EmosewaGamer** [comment]
Why does it say in the config that it disables them then?

**Comment by elucent** [comment]
Probably a mistake. I'll have this fixed in an update in a little bit anyway.
