### ISSUE TITLE
Suggetion: change how item gauge displays some inventories

### ISSUE THREAD

**Issue by Reoseah** [RootsTeam/Embers#21]
I'd placed Item Gauge on chest and got this:
![2016-10-16_14 05 53](https://cloud.githubusercontent.com/assets/20323084/19417025/49eb0996-93aa-11e6-9a6c-e8f1791ec5f9.png)
As for me, it seems definitely broken...

I suggest check number of slots in inventory and if there is more than four or five, then only display some summary information. Something like "Filled 3 of 27 slots".

For blocks like furnace, naming slots would be better then numbering.
I mean something like this:

```
Input slot: ***
Output slot: ***
Fuel slot: ***
```

Perhaps, it can be done through capability like this:

``` java
public interface ISlotNameProvider {
  String getName(IItemHandler handler, int index);
  // perhaps 
  // boolean isDisplayed(IItemHandler handler, int index);
}
```

Or it can be something more general when user will provide all lines for display.
Both ways, other mods could support item gauge in nicer ways.

**Comment by elucent** [comment]
I need to figure out a better way to make it in general, currently it's just there to be consistent with the other two gauges, but it's definitely got some issues. Making it just show "filled x out of y slots" is a good idea.
