### ISSUE TITLE
Item Transfer Not Passing Items Through v0.215 & 0.216 & 0.219

### ISSUE THREAD

**Issue by finder1212** [RootsTeam/Embers#218]
The item transfer block is not filtering items in versions **0.215** and **0.216.** If placed on top of the item pipes the selected item flows past and if placed at the end of a pipe it simply blocks all times, including the intended ones. The item transfer works in version 0.214 even when the same world file is loaded.

**Comment by elucent** [comment]
Post a picture of your setup?

**Comment by finder1212** [comment]
If you worked on it 2 days ago then I guess I missed the update but here's my setup and how I tested it:
Note: Embers is the only mod installed. **Forge v13.20.1.2388**. Hope this helps!

Tested it in 0.214
![](https://cdn.discordapp.com/attachments/219532583552286720/330534407167279104/2017-06-30_21.15.43.png)
![](https://cdn.discordapp.com/attachments/219532583552286720/330534761456205824/2017-06-30_21.15.55.png)

As well as the 0.216 test
![](https://cdn.discordapp.com/attachments/219532583552286720/330534535412580372/2017-06-30_21.18.56.png)
![](https://cdn.discordapp.com/attachments/219532583552286720/330534538524753920/2017-06-30_21.19.07.png)

**Comment by finder1212** [comment]
Small Update
v0.219
![2017-06-30_22 00 18](https://user-images.githubusercontent.com/29764366/27758667-bc175baa-5ddf-11e7-90f6-52e56d694442.png)

**Comment by elucent** [comment]
@finder1212 the transfer in that picture is facing the wrong way.

**Comment by darkshadow543** [comment]
I'm having the same issue, but its letting blacklisted items through. Maybe your missing an exclamation point somewhere(I know coding too).
![2017-07-02_20 03 37](https://user-images.githubusercontent.com/14943673/27774546-586b17de-5f62-11e7-8d16-791543e43a97.png)
![2017-07-02_20 04 06](https://user-images.githubusercontent.com/14943673/27774547-5bcd31fa-5f62-11e7-831e-c6d891887b14.png)
Here is my setup, coal is going into the ember chest.

**Comment by elucent** [comment]
Ah yes, that is a bug. Try clicking multiple times to set the filter in the meantime, it's a sync-related problem and I'll have a fix out shortly.
