### ISSUE TITLE
Very slow world tick handler

### ISSUE THREAD

**Issue by sfPlayer1** [RootsTeam/Embers#220]
On FC1 with Embers 0.216/MC 1.11.2 teamroots.embers.EventManager.onWorldTick takes about 65 ms every tick. It's all onWorldTick self time including inlined methods. The problem seems to develop gradually the longer the server runs, even though the total loaded te count apparently grows only moderately (< 2x).

It's generally a bad idea to iterate the world's te list frequently.

**Comment by elucent** [comment]
Whoops. Yeah, I keep coming back to Embers and seeing bits I should have written better.

I'll swap it so that TEs get put on a map when marked dirty and then added to the list, instead of checking every TE in the game. :P

**Comment by elucent** [comment]
Okay, implemented a fix, will release a new build soon. Let me know if it helps.

**Comment by elucent** [comment]
Closing this because I haven't heard anything since.
