### ISSUE TITLE
Found a warning in 1.12

### ISSUE THREAD

**Issue by Sparksolur** [RootsTeam/Embers#225]
I found these lines in the game output screen while loading up Embers in 1.12, and thought you might be interested. Also, it told me to tell you and I haven't seen this one reported after checking on four different sites, so here you go:

https://pastebin.com/55sRgSTU

**Comment by elucent** [comment]
Thanks. I should have a fix out relatively soon.

**Comment by elucent** [comment]
Should be fixed in 0.230.
