### ISSUE TITLE
[1.11.2 - 0.219] Embers Melter returns no liquid metal when used properly

### ISSUE THREAD

**Issue by GeekBeam** [RootsTeam/Embers#226]
very simple bug to reproduce, put a metal ingot into the melter and have it melt the ingot. there will be no liquid in the melter to take out. verified with the use of The One Probe.

**Comment by elucent** [comment]
Did we discuss this and resolve this? I forget tbh. :P

**Comment by GeekBeam** [comment]
Yes we did, i was a dumb and had an extractor powered. Closing this thread.

**Comment by elucent** [comment]
No problem, it happens to the best of us. :P
