### ISSUE TITLE
Crashing when right-clicking with battle axe

### ISSUE THREAD

**Issue by Compegen** [RootsTeam/Embers#23]
I've been testing a modpack I have for possible breaks and this was one I randomly found: http://pastebin.com/ag5z5YBK

With just Embers & JEI installed: http://pastebin.com/E6z54nFa

____

Happens when right-clicking block

**Comment by Reoseah** [comment]
@Compegen It seems this item is not battleaxe at all... It is named ItemDebug... 
In short, it tries to teleport player to some dimension, which is not created. 
That's either something in progress or something from saved from older experiments. Maybe Elucent or somebody else from their team just needed place to insert some code and be able to execute that on demand, and this place was `onItemActivated` of that "axe"

**Comment by elucent** [comment]
Yeah, there's a reason that's not implemented in the mod yet. It's not even in the creative tab, it's an unimplemented item and it's your fault that it crashed.

I'll be giving it functionality soon, this is not a bug.

**Comment by Reoseah** [comment]
It is Shrödinger Axe:
It is implemented.
It is not implemented.
You don't know what it really is untill you obtain it.
Right-clicking with it forces it to decide its state.
So, you are crashing game by right-clicking.
It's your fault ;3
