### ISSUE TITLE
[1.11.2 v0.219] Fairy causing client crash on Server

### ISSUE THREAD

**Issue by VallenFrostweaver** [RootsTeam/Embers#233]
Fairies are spawning in a pool near me while I was taking cold damage from Tough as Nails at night. See pastebin below.
https://pastebin.com/WzQUeiF5

**Comment by elucent** [comment]
Roots bug, not Embers bug. :P

There's an issue on the Roots GitHub about this. I don't believe I can fix it on my end and it's very tricky to track down. If you get any more information on this please let me know, but unfortunately it's likely some obscure mod interaction.

**Comment by VallenFrostweaver** [comment]
ah flaf. XP
