### ISSUE TITLE
Feature Request: Archaic Bricks Block

### ISSUE THREAD

**Issue by benserwa** [RootsTeam/Embers#246]
Playing Modern Skyblock 2, and I've got so many of these damn Archaic Bricks because mob farming is such a necessity from the very early game, and all I want is to be able to craft them together in a 2x2 and make a cosmetic Archaic Bricks block so I could build stuff with them.

**Comment by elucent** [comment]
That exists. It literally exists. Did you think it didn't?

**Comment by benserwa** [comment]
Well, I tried to craft it and it didn't craft, then I tried to look it up
in JEI and it wasn't there.

**Comment by Xenonix** [comment]
I just was bussy building my base in the End with this and no it isnt in there. xD Not 2x2, or 3x3.
And cant find it in JEI. (Beyond The New Frontier pack). But i LOVE this mod. its soo cool :D

**Comment by elucent** [comment]
...huh. Well, the block exists, but the recipe seems to be broken somehow. If I ever update Embers again I'll fix this.

**Comment by alexpic57** [comment]
should also be added the archaic bricks (block) to archaic brick (item) ?

**Comment by elucent** [comment]
Should be fixed in 0.230.
