### ISSUE TITLE
Grandhammer does not accept Intelligent Apparatus

### ISSUE THREAD

**Issue by Johannason** [RootsTeam/Embers#252]
After giving the Grandhammer a Heat bar and Inferno Forging it, I can't put an Intelligent Apparatus on it. As the seemingly-primary melee weapon of Embers, I figured it should be modifiable with bonus XP. Especially since it treats the Blast Core as a weapon modifier rather than a tool modifier.

**Comment by elucent** [comment]
It's an armor augment.
