### ISSUE TITLE
[1.11.2] java.lang.RuntimeException: Please use the iterator instead

### ISSUE THREAD

**Issue by Arkyo** [RootsTeam/Embers#255]
[pastebin](https://pastebin.com/EuiZSwYK)

**Comment by elucent** [comment]
Not fixing this, this is on CreativeCore and I believe it's been fixed on their end since.

**Comment by Arkyo** [comment]
Yep [https://github.com/CreativeMD/CreativeCore/issues/26](The issue I gave to CreativeMD)
