### ISSUE TITLE
[1.12] The Creative Ember Source doesn't work

### ISSUE THREAD

**Issue by EmosewaGamer** [RootsTeam/Embers#262]
The Creative Ember Source isn't working. If you're wondering why this is a problem, the reason is that it's one of the obtainable creative items in my pack.

**Comment by DaedalusGame** [comment]
uhm... it does tho

**Comment by EmosewaGamer** [comment]
How? Emitters connected to it don't seem work.

**Comment by DaedalusGame** [comment]
Activate the Emitters with a lever.

**Comment by EmosewaGamer** [comment]
Weird. I even though I know that that's how Embers works, for some reason I forgot that when testingthe creative ember source.
