### ISSUE TITLE
No “Eye of the Ancient” drop?

### ISSUE THREAD

**Issue by PapiDimmi** [RootsTeam/Embers#267]
No matter how many times I kill an ancient golem with a pickaxe, I don’t get this item. It doesn’t appear in JEI either.

****

**Minecraft version**: 1.12.2
**Embers version**: 0.230

**Comment by Dragnier** [comment]
This was changed in a version after 1.10. You now make the manual by using the drops of the Golem and don't need to kill it with the pick anymore. Just look up the manual/tablet in JEI for the recipe.

I highly suggest you watch the videos by Mischief of Mice on YouTube about the 1.12 version changes.

**Comment by PapiDimmi** [comment]
@Dragnier Oh, thanks. The [project page](https://minecraft.curseforge.com/projects/embers) should include this information.
