### ISSUE TITLE
clockwork tools abilities not working

### ISSUE THREAD

**Issue by radiocrack** [RootsTeam/Embers#268]
In version 0.230 on 1.12 None of the clockwork tools or grand hammer Right-click abilities work.  FTB Horizons iii pack. also tried in embers craft 1.12 pack.

The right click with staff and ray work fine.

**Comment by elucent** [comment]
This has been reported so many times lol. These were removed almost a year ago. No part of the mod describes right-click abilities currently and no part has since 1.10.
