### ISSUE TITLE
Plates not balanced for interactions with other mods

### ISSUE THREAD

**Issue by SPMoo66** [RootsTeam/Embers#27]
Your plates have ore dictionary entries for plate(Material) and cost four ingots of the material, yet most mods have balanced the plate(Material) entry around plates being one ingot.
Tinkers melts plates down for one ingot of molten metal. Immersive Engineering plates can be swapped into your recipes, but only cost one ingot of their respective material.
I understand the balance you're trying to create in Embers, but because of the ore dictionary the balance is easily broken by a few other mods.

**Comment by Reoseah** [comment]
https://github.com/RootsTeam/Embers/issues/13 copy issue.

**Comment by elucent** [comment]
Whether or not you choose to use other mods to make plates a little cheaper is no concern of mine. You can do whatever you want, I balance Embers independently of other mods for the most part, and ultimately it doesn't really break progression much other than you might have slightly less motivation to make a plate press.
