### ISSUE TITLE
Grandhammer related crash in creative

### ISSUE THREAD

**Issue by TheCorruption** [RootsTeam/Embers#30]
I crashed after killing an armadillo from Quintessential Creatures with a blazing ray in creative, but it seems that the crash is from the grandhammer, I also had a filled mantle jar equipped if it helps, tested on 0.013

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-56.jar)
  LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.1.101-universal.jar)
  CCCDeobfPlugin (unknown)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.3.2.82-universal.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 11/1/16 12:40 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at teamroots.embers.util.EmberInventoryUtil.getEmberTotal(EmberInventoryUtil.java:49)
	at teamroots.embers.item.ItemGrandhammer.func_77663_a(ItemGrandhammer.java:165)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:441)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:344)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:510)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:959)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2019)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:167)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.World.func_72870_g(World.java:1934)
	at net.minecraft.world.World.func_72939_s(World.java:1750)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at teamroots.embers.util.EmberInventoryUtil.getEmberTotal(EmberInventoryUtil.java:49)
	at teamroots.embers.item.ItemGrandhammer.func_77663_a(ItemGrandhammer.java:165)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:441)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:344)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:510)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:959)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2019)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:167)
	at net.minecraft.world.World.func_72866_a(World.java:1964)
	at net.minecraft.world.World.func_72870_g(World.java:1934)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 1100
	Entity Name: The_corruption
	Entity's Exact location: 633.80, 71.83, 165.86
	Entity's Block location: World: (633,71,165), Chunk: (at 9,4,5 in 39,10; contains blocks 624,0,160 to 639,255,175), Region: (1,0; contains chunks 32,0 to 63,31, blocks 512,0,0 to 1023,255,511)
	Entity's Momentum: -0.26, 0.02, -0.47
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1750)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['The_corruption'/1100, l='MpServer', x=633.80, y=71.83, z=165.86]]
	Chunk stats: MultiplayerChunkCache: 618, 618
	Level seed: 0
	Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (156,64,297), Chunk: (at 12,4,9 in 9,18; contains blocks 144,0,288 to 159,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 44384 game time, 44384 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 99 total; [EntitySpider['Spider'/53292, l='MpServer', x=684.01, y=69.00, z=193.99], EntitySpider['Spider'/53345, l='MpServer', x=712.02, y=66.00, z=167.01], EntitySpider['Spider'/53354, l='MpServer', x=694.73, y=68.00, z=180.71], EntityFestiveCreeper['Festive Creeper'/53457, l='MpServer', x=710.50, y=48.00, z=125.50], EntityCreeper['Creeper'/53513, l='MpServer', x=687.15, y=65.00, z=164.15], EntityZombie['Zombie'/53519, l='MpServer', x=676.50, y=42.00, z=118.50], EntityRabbit['Rabbit'/53726, l='MpServer', x=558.07, y=68.00, z=206.93], EntityItem['item.item.ingotIron'/53737, l='MpServer', x=663.32, y=64.00, z=198.39], EntityBlowfish['Blowfish'/53754, l='MpServer', x=669.03, y=62.00, z=188.55], EntityEnchantedBook['Bewitched Tome'/53882, l='MpServer', x=665.50, y=33.00, z=122.50], EntitySquid['Squid'/53911, l='MpServer', x=660.13, y=58.19, z=182.41], EntitySquid['Squid'/53912, l='MpServer', x=664.24, y=62.22, z=188.54], EntitySquid['Squid'/53913, l='MpServer', x=676.58, y=62.34, z=187.42], EntityHauntedTool['Haunted Tool'/54152, l='MpServer', x=650.90, y=62.12, z=148.88], EntityHauntedTool['Haunted Tool'/54153, l='MpServer', x=666.50, y=30.00, z=183.50], EntityBat['Bat'/54176, l='MpServer', x=640.05, y=31.59, z=242.96], EntityBat['Bat'/54190, l='MpServer', x=685.44, y=22.00, z=159.65], EntitySpider['Spider'/54286, l='MpServer', x=640.50, y=31.00, z=235.50], EntityZombie['Husk'/54303, l='MpServer', x=687.27, y=69.00, z=243.53], EntityCreeper['Creeper'/54311, l='MpServer', x=676.50, y=17.00, z=179.50], EntityEnchantedBook['Bewitched Tome'/54331, l='MpServer', x=651.09, y=38.00, z=183.67], EntityBat['Bat'/54369, l='MpServer', x=622.02, y=43.00, z=198.15], EntityRabbit['Rabbit'/50289, l='MpServer', x=580.06, y=65.00, z=150.62], EntityRabbit['Rabbit'/50290, l='MpServer', x=581.30, y=66.00, z=156.30], EntityRabbit['Rabbit'/50291, l='MpServer', x=582.30, y=66.00, z=159.30], EntityArmadillo['Armadillo'/54420, l='MpServer', x=601.16, y=67.00, z=183.75], EntityArmadillo['Armadillo'/54464, l='MpServer', x=622.73, y=63.00, z=218.55], EntityEnchantedBook['Bewitched Tome'/54509, l='MpServer', x=648.50, y=32.00, z=176.50], EntityRabbit['Rabbit'/25861, l='MpServer', x=641.43, y=65.00, z=108.52], EntityCreeper['Creeper'/54555, l='MpServer', x=675.64, y=49.00, z=169.93], EntityCreeper['Creeper'/54557, l='MpServer', x=670.65, y=49.00, z=169.43], EntitySkeleton['Skeleton'/54575, l='MpServer', x=637.54, y=21.00, z=223.22], EntityZombie['Zombie'/54579, l='MpServer', x=639.50, y=26.00, z=221.50], EntitySkeleton['Skeleton'/54581, l='MpServer', x=655.50, y=37.00, z=119.50], EntitySkeleton['Skeleton'/54583, l='MpServer', x=650.50, y=37.00, z=121.50], EntityFestiveCreeper['Festive Creeper'/54686, l='MpServer', x=665.50, y=29.00, z=176.50], EntityOctopus['Octopus'/54696, l='MpServer', x=591.53, y=61.56, z=100.35], EntityXPOrb['Experience Orb'/54702, l='MpServer', x=694.54, y=67.00, z=178.02], EntityXPOrb['Experience Orb'/54703, l='MpServer', x=696.70, y=67.00, z=177.17], EntityRabbit['Rabbit'/26033, l='MpServer', x=629.40, y=62.71, z=119.29], EntityTreasureSlime['Treasure Slime'/54715, l='MpServer', x=636.30, y=65.67, z=112.34], EntityTreasureSlime['Treasure Slime'/54742, l='MpServer', x=694.64, y=69.75, z=234.06], EntityEnchantedBook['Bewitched Tome'/54747, l='MpServer', x=653.50, y=16.00, z=99.50], EntityBat['Bat'/54786, l='MpServer', x=657.48, y=35.10, z=110.62], EntityBat['Bat'/54787, l='MpServer', x=677.60, y=33.12, z=124.10], EntityBlowfish['Blowfish'/54914, l='MpServer', x=624.26, y=60.67, z=132.77], EntityFilchLizard['Filch Lizard'/54922, l='MpServer', x=635.50, y=64.00, z=233.50], EntityArmadillo['Armadillo'/54933, l='MpServer', x=597.26, y=65.00, z=128.50], EntityPlayerSP['The_corruption'/1100, l='MpServer', x=633.80, y=71.83, z=165.86], EntityRocketCreeper['Rocket Creeper'/55037, l='MpServer', x=689.50, y=24.00, z=139.50], EntityFestiveCreeper['Festive Creeper'/55038, l='MpServer', x=667.50, y=48.00, z=154.50], EntityFestiveCreeper['Festive Creeper'/55041, l='MpServer', x=671.50, y=53.00, z=196.50], EntityHauntedTool['Haunted Tool'/55064, l='MpServer', x=564.55, y=49.00, z=180.64], EntityTreasureSlime['Treasure Slime'/55072, l='MpServer', x=566.61, y=35.00, z=107.57], EntityBat['Bat'/55113, l='MpServer', x=636.96, y=19.08, z=183.64], EntityBat['Bat'/55134, l='MpServer', x=617.75, y=31.52, z=206.74], EntityHauntedTool['Haunted Tool'/55146, l='MpServer', x=691.50, y=39.00, z=177.50], EntityBlowfish['Blowfish'/55168, l='MpServer', x=583.52, y=62.00, z=134.31], EntityBat['Bat'/55190, l='MpServer', x=654.39, y=27.40, z=175.71], EntityFilchLizard['Filch Lizard'/55224, l='MpServer', x=610.50, y=64.00, z=132.50], EntityTreasureSlime['Treasure Slime'/55282, l='MpServer', x=676.02, y=34.00, z=120.78], EntityEnderman['Enderman'/51194, l='MpServer', x=713.29, y=66.00, z=181.72], EntitySkeleton['Skeleton'/55295, l='MpServer', x=707.50, y=66.00, z=139.50], EntityCreeper['Creeper'/55304, l='MpServer', x=561.49, y=72.00, z=239.16], EntityCreeper['Creeper'/55305, l='MpServer', x=566.17, y=68.00, z=215.87], EntityZombie['Zombie'/55313, l='MpServer', x=567.50, y=64.00, z=117.50], EntityRocketCreeper['Rocket Creeper'/55325, l='MpServer', x=704.50, y=50.00, z=120.50], EntityEnchantedBook['Bewitched Tome'/55331, l='MpServer', x=709.50, y=12.00, z=226.50], EntityEnchantedBook['Bewitched Tome'/55333, l='MpServer', x=556.50, y=21.00, z=116.50], EntityArmadillo['Armadillo'/55339, l='MpServer', x=649.69, y=61.00, z=147.69], EntityRocketCreeper['Rocket Creeper'/55347, l='MpServer', x=684.50, y=28.00, z=131.50], EntityRocketCreeper['Rocket Creeper'/55349, l='MpServer', x=687.50, y=28.00, z=146.50], EntitySupportCreeper['Support Creeper'/55350, l='MpServer', x=692.58, y=26.00, z=134.81], EntitySupportCreeper['Support Creeper'/55352, l='MpServer', x=567.50, y=40.00, z=110.50], EntitySupportCreeper['Support Creeper'/55354, l='MpServer', x=624.50, y=21.00, z=219.50], EntityRabbit['Rabbit'/26692, l='MpServer', x=659.69, y=71.00, z=93.98], EntityRabbit['Rabbit'/26693, l='MpServer', x=665.91, y=70.00, z=93.25], EntityRocketCreeper['Rocket Creeper'/55410, l='MpServer', x=635.50, y=35.00, z=218.50], EntityBlowfish['Blowfish'/55417, l='MpServer', x=684.76, y=60.91, z=91.94], EntityBat['Bat'/55439, l='MpServer', x=604.19, y=65.99, z=143.33], EntityBat['Bat'/55440, l='MpServer', x=600.25, y=63.10, z=144.25], EntityBat['Bat'/55447, l='MpServer', x=692.47, y=47.92, z=143.52], EntityBat['Bat'/55448, l='MpServer', x=687.83, y=40.03, z=141.92], EntityBat['Bat'/55449, l='MpServer', x=649.29, y=57.70, z=114.48], EntityRocketCreeper['Rocket Creeper'/55472, l='MpServer', x=627.50, y=39.00, z=122.50], EntityArmadillo['Armadillo'/55481, l='MpServer', x=688.46, y=65.00, z=165.69], EntityArmadillo['Armadillo'/55482, l='MpServer', x=591.69, y=65.00, z=168.51], EntityZombie['entity.Zombie.name'/55489, l='MpServer', x=704.50, y=66.00, z=142.50], EntityZombie['entity.Zombie.name'/55490, l='MpServer', x=705.50, y=66.00, z=142.50], EntityTreasureSlime['Treasure Slime'/55506, l='MpServer', x=623.74, y=63.00, z=225.30], EntitySkeleton['Skeleton'/55522, l='MpServer', x=674.50, y=66.00, z=119.50], EntitySkeleton['Skeleton'/55529, l='MpServer', x=644.50, y=31.00, z=235.50], EntityEnderman['Enderman'/55540, l='MpServer', x=665.50, y=31.00, z=199.50], EntitySkeleton['Skeleton'/55552, l='MpServer', x=686.50, y=68.00, z=215.50], EntityEnchantedBook['Bewitched Tome'/55571, l='MpServer', x=608.50, y=17.00, z=209.50], EntityRabbit['Rabbit'/52374, l='MpServer', x=568.50, y=64.00, z=173.50], EntityRabbit['Rabbit'/52375, l='MpServer', x=569.30, y=64.00, z=173.30], EntityRabbit['Rabbit'/52377, l='MpServer', x=569.40, y=66.00, z=177.40], EntityBat['Bat'/52993, l='MpServer', x=705.25, y=32.10, z=175.75]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 310596504 bytes (296 MB) / 1080033280 bytes (1030 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.32 Powered by Forge 12.18.1.2095 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2095.jar) 
	UCHIJAAAA	Forge{12.18.1.2095} [Minecraft Forge] (forge-1.10.2-12.18.1.2095.jar) 
	UCHIJAAAA	CodeChickenCore{2.3.2.82} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	antiqueatlas{1.9.4-4.3.0} [Antique Atlas] (antiqueatlas-1.9.4-4.3.0.jar) 
	UCHIJAAAA	AntiqueAtlasOverlay{1.2} [AntiqueAtlasOverlay] (antiqueatlas-1.9.4-4.3.0.jar) 
	UCHIJAAAA	JEI{3.12.6.304} [Just Enough Items] (jei_1.10.2-3.12.6.304.jar) 
	UCHIJAAAA	appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
	UCHIJAAAA	Quark{r1.0-56} [Quark] (Quark-r1.0-56.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	Baubles{1.3.BETA11} [Baubles] (Baubles-1.10.2-1.3.BETA11.jar) 
	UCHIJAAAA	BiomesOPlenty{5.0.0.2089} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2089-universal.jar) 
	UCHIJAAAA	Bloodmoon{1.2} [Bloodmoon] (Bloodmoon-MC1.9.4-1.4.1.jar) 
	UCHIJAAAA	Bullseye{1.0.3} [Bullseye] (Bullseye-1.9.4-1.0.3.jar) 
	UCHIJAAAA	dispensergun{1.10-0.1} [Dispenser Gun] (dispensergun-1.10-0.1.jar) 
	UCHIJAAAA	embers{0.013} [Embers] (embers-0.013.jar) 
	UCHIJAAAA	EnderStorage{2.1.5.80} [EnderStorage] (EnderStorage-1.10.2-2.1.5.80-universal.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJAAAA	jeresources{0.5.1.56} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.1.56.jar) 
	UCHIJAAAA	mcmultipart{1.2.1} [MCMultiPart] (MCMultiPart-1.2.1-universal.jar) 
	UCHIJAAAA	primitivemobs{1.1} [Primitive Mobs] (primitivemobs-1.1-alpha.jar) 
	UCHIJAAAA	qcreatures{2.0.1} [Quintessential Creatures] (qcreatures-2.0.1.jar) 
	UCHIJAAAA	Quartzly{0.3} [Quartzly] (Quartzly0.3.jar) 
	UCHIJAAAA	refinedstorage{1.1.3} [Refined Storage] (refinedstorage-1.1.3.jar) 
	UCHIJAAAA	roots{0.204} [Roots] (roots-1.10.2-0.204.0.jar) 
	UCHIJAAAA	spartanshields{1.0} [Spartan Shields] (SpartanShields-1.10.2-1.0.jar) 
	UCHIJAAAA	waddles{0.5.0} [Waddles] (Waddles-1.10.2-0.5.0.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.206.jar) 
	UCHIJAAAA	wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.206.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-56.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.1.101-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CCCDeobfPlugin (unknown)
  
CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.3.2.82-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1065.0' Renderer: 'AMD RADEON HD 6350'
	CodeChickenCore: ignoreInvalidMCVersion state: false
	Launched Version: forge-12.18.1.2095
	LWJGL: 2.9.4
	OpenGL: AMD RADEON HD 6350 GL version 4.5.13399 Compatibility Profile Context 15.200.1065.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz

**Comment by elucent** [comment]
Same bug as #29, fixed it! A new version will be out shortly.
