### ISSUE TITLE
Server Crash when charging Cartridge in Charger TE

### ISSUE THREAD

**Issue by p455w0rd** [RootsTeam/Embers#31]
![Server Crash](https://cloud.githubusercontent.com/assets/12187748/19921607/0023c862-a0b5-11e6-90ab-f4a2b763d322.png)

**Comment by p455w0rd** [comment]
submitted #23 to fix this

**Comment by elucent** [comment]
I've already fixed this in my dev environment, I'll release a new build shortly.
