### ISSUE TITLE
Minor - Looking at an ember gauge causes the armor HUD icons to display incorrectly

### ISSUE THREAD

**Issue by Febilian** [RootsTeam/Embers#35]
http://i.imgur.com/ZJjLRVC.png

It reverts to normal armor icons when I look away/untarget the gauge. It works on more than just this one too, it does it with any gauge I look at for some reason.

I can try to provide more info if needed or if this cannot be reproduced.

**Comment by rotovap** [comment]
I have had a similar problem to this. My hunger icons display as white boxes while looking at gauges. It is the same for every gauge.

Not looking at gauge:
[http://i.imgur.com/ocXkzY9.png](url)
Looking at gauge:
[http://i.imgur.com/xCIaUR6.png](url)

**Comment by Reoseah** [comment]
Maybe something like this at the end of the text rendering method could help:
```java
Minecraft.getMinecraft().getTextureManager().bindTexture(new ResourceLocation("minecraft:textures/gui/icons.png"));
```

**Comment by elucent** [comment]
Might have fixed this, let me check.

**Comment by elucent** [comment]
Yep, fixed.
