### ISSUE TITLE
Stamper unlimited ingots

### ISSUE THREAD

**Issue by Meller127** [RootsTeam/Embers#38]
The stamper produces unlimited iron ingots, not tested with Another material. I inserted 2 iron ore in to the smeltery and pumped it in the stamper base. 288mb. It still going strong after 300+ ingots.

![2016-11-19_16 37 07](https://cloud.githubusercontent.com/assets/13392710/20456417/a8c3d38a-ae76-11e6-9fe4-93ab225878a8.png)

![2016-11-19_16 39 52](https://cloud.githubusercontent.com/assets/13392710/20456429/d52ce24a-ae76-11e6-8f45-03dae4a92c1b.png)

Mc: 1.10.2
Forge: 2125
Embers: 0.016
Server: Yes
Modpack: All the mods Expert

**Comment by elucent** [comment]
Strange. I've not encountered this myself. I'll take a look when I finish up the next Roots update.

**Comment by elucent** [comment]
This might have been fixed? Let me know if anything changes when I get the next version out.

**Comment by al132** [comment]
It looks like someone has brought up a similar issue again
https://github.com/whatthedrunk/allthemods/issues/350

**Comment by elucent** [comment]
I believe I've fixed this in my IDE, but I also have a lot of somewhat incomplete content in the works, so unfortunately a fix will have to wait. Sorry, but hopefully it won't be too long!

**Comment by elucent** [comment]
This should be fixed in the new version, which will be uploaded shortly.
