### ISSUE TITLE
EnderIO conduit and Ember's Pump not getting along

### ISSUE THREAD

**Issue by belathus** [RootsTeam/Embers#49]
This might be EIO's fault, as it worked in EIO version 3.0.1.136 (I updated to 3.0.1.137). The version of Embers is 0.016.

http://pastebin.com/raw/fXCZ0r9y

**Comment by elucent** [comment]
I've seen this happen before. It's not too hard to fix, but it's a little weird that it's happening.

**Comment by elucent** [comment]
Fixed.

**Comment by belathus** [comment]
Awesome. Thank you, sir.

**Comment by elucent** [comment]
I'm accumulating a bunch of bug fixes for the next release. It might be a little while, but it's gonna improve a lot of aspects of the mod. Documentation for one example.
