### ISSUE TITLE
Eye of the ancients doesnt animate correctly when in off-hand

### ISSUE THREAD

**Issue by TheCorruption** [RootsTeam/Embers#51]
When you look at a block with the eye, it wont open, but the description will show.
![2016-12-30_20 06 24](https://cloud.githubusercontent.com/assets/22695945/21575275/a301ff64-cecc-11e6-81f9-f7546a548273.png)

**Comment by elucent** [comment]
I'm...actually not sure if this is fixable. Or at least not without totally redoing the animation for the eye.

**Comment by charlie-e09ae35d** [comment]
If it helps anything I noticed that eye animation triggers correctly when first toolbar slot is selected (while eye is offhand).

**Comment by elucent** [comment]
Yeah, I'm just gonna close this. It's minor enough that the effort needed to try and fix this vastly outstrips the problem itself.
