### ISSUE TITLE
[Suggestion] Tiered Ember refinement

### ISSUE THREAD

**Issue by Dragnier** [RootsTeam/Embers#55]
Basic mining of Ember is definitely well handled. I love the mechanic. However, as the mod progresses you may want to consider other ways to obtain Ember that don't require coal. One possible way to do that is a refinement process which allows for crystallization of Ember that can only be fueled by Ember; basically making you have to reach a certain amount of mined Ember to start the process. Then, balancing the refinement process so that you have to be careful how it is done or you might even lose Ember, but done correctly produces far more than it uses.

**Comment by TheCorruption** [comment]
Check "Projects".

**Comment by elucent** [comment]
I have a few ideas floating around for better Ember yields, not sure exactly what'll get added, but expect _something_ eventually.

**Comment by elucent** [comment]
Basically been implemented.
