### ISSUE TITLE
[Suggestion] Clear pipe alternatives at higher tiers

### ISSUE THREAD

**Issue by Dragnier** [RootsTeam/Embers#58]
One of the most awesome things in many mods is actually seeing items or fluids move through pipes. While I understand this is an alpha and this is probably not something basic pipes should do, I think it would be a worthwhile addition to consider for later on.

**Comment by elucent** [comment]
It would be cool, but I have two issues with it:

1) I like the idea that Embers stuff is kind of opaque and heavy. There's not a lot of transparency in the mod, and I think it lends it a nice kind of visual feel, very material and mechanical. So I'm not sure of a good way to introduce transparency to the pipes without compromising that.

2) Rendering items running through the pipes would be tricky, and also increase the FPS lag per pipe considerably. I already have a few people on my case about how I render pipe connections, rendering items running through the pipes would make them significantly less performant.

Still, I'll leave this issue open in case I ever change my mind.

**Comment by Dragnier** [comment]
Yeah, I do understand. That's why I suggested it as non-basic for optional purely cosmetic reasons at higher tiers. Even if it were just a line of glass down the length of the pipe on the cardinal directions, I think it would be enough. But, I totally get your point of view!
