### ISSUE TITLE
Ancient Golem kills with Tinker picks don't drop...<spoiler>

### ISSUE THREAD

**Issue by VallenFrostweaver** [RootsTeam/Embers#59]
Eye of the Ancients.  Seems to drop for other mod picks. Not sure if this is a Tinkers' issue or Embers?

**Comment by elucent** [comment]
I'm pretty sure it's a Tinkers' issue technically, they probably aren't extending the ItemPickaxe class for their tools. I might be able to add support for them by using a different means of detecting if something is a pickaxe, though.
