### ISSUE TITLE
Crash when placing lots of ember emitters on top of each other

### ISSUE THREAD

**Issue by TheCorruption** [RootsTeam/Embers#6]
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 10/7/16 9:16 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at teamroots.embers.EventManager.onGameOverlayRender(EventManager.java:194)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_7_EventManager_onGameOverlayRender_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:888)
    at net.minecraftforge.client.GuiIngameForge.renderHelmet(GuiIngameForge.java:268)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:133)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1072)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at teamroots.embers.EventManager.onGameOverlayRender(EventManager.java:194)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_7_EventManager_onGameOverlayRender_Post.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168)
    at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:888)
    at net.minecraftforge.client.GuiIngameForge.renderHelmet(GuiIngameForge.java:268)
    at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:133)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['The_corruption'/95, l='MpServer', x=617.68, y=66.31, z=356.95]]
    Chunk stats: MultiplayerChunkCache: 553, 553
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options:
    Level spawn location: World: (156,64,248), Chunk: (at 12,4,8 in 9,15; contains blocks 144,0,240 to 159,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 16668 game time, 16668 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 107 total; [EntityBat['Bat'/14593, l='MpServer', x=670.25, y=31.00, z=345.78], EntitySpider['Spider'/14083, l='MpServer', x=663.80, y=66.00, z=401.83], EntitySpider['Spider'/14084, l='MpServer', x=661.10, y=66.00, z=405.41], EntityBat['Bat'/13830, l='MpServer', x=586.30, y=19.07, z=411.64], EntityCreeper['Creeper'/14086, l='MpServer', x=546.50, y=67.00, z=309.50], EntityZombie['Zombie'/14345, l='MpServer', x=566.50, y=9.00, z=293.50], EntityZombie['Zombie'/14348, l='MpServer', x=564.50, y=9.00, z=295.50], EntityCreeper['Creeper'/14349, l='MpServer', x=566.50, y=9.00, z=295.50], EntityZombie['Zombie'/13334, l='MpServer', x=607.30, y=64.00, z=342.81], EntityZombie['Zombie'/14616, l='MpServer', x=623.50, y=64.00, z=325.50], EntityZombie['Zombie'/14617, l='MpServer', x=625.50, y=64.00, z=326.50], EntityZombie['Zombie'/14619, l='MpServer', x=627.50, y=64.00, z=331.50], EntityCreeper['Creeper'/14624, l='MpServer', x=613.83, y=64.00, z=318.83], EntitySheep['Sheep'/11564, l='MpServer', x=657.50, y=63.00, z=341.50], EntityZombie['Zombie'/14125, l='MpServer', x=586.50, y=19.00, z=317.50], EntitySheep['Sheep'/11565, l='MpServer', x=672.48, y=65.00, z=338.23], EntityZombie['Zombie'/14126, l='MpServer', x=586.50, y=19.00, z=317.50], EntityZombie['Zombie'/14127, l='MpServer', x=584.50, y=20.00, z=311.77], EntityCreeper['Creeper'/14129, l='MpServer', x=661.50, y=65.00, z=389.50], EntityCreeper['Creeper'/14130, l='MpServer', x=661.50, y=65.00, z=390.50], EntitySheep['Sheep'/11316, l='MpServer', x=588.39, y=68.00, z=405.21], EntityZombie['Zombie'/14132, l='MpServer', x=668.50, y=65.00, z=391.50], EntitySheep['Sheep'/11317, l='MpServer', x=579.77, y=69.00, z=416.33], EntitySheep['Sheep'/11318, l='MpServer', x=584.82, y=67.00, z=408.53], EntitySheep['Sheep'/11319, l='MpServer', x=587.30, y=68.00, z=405.53], EntitySheep['Sheep'/11329, l='MpServer', x=626.50, y=74.00, z=429.50], EntitySheep['Sheep'/11330, l='MpServer', x=623.50, y=74.00, z=429.55], EntitySheep['Sheep'/11331, l='MpServer', x=618.72, y=72.00, z=427.46], EntityZombie['Zombie'/14405, l='MpServer', x=554.51, y=68.00, z=370.19], EntityCreeper['Creeper'/14407, l='MpServer', x=613.73, y=64.00, z=322.15], EntityCreeper['Creeper'/14408, l='MpServer', x=607.78, y=64.00, z=319.44], EntityBat['Bat'/14680, l='MpServer', x=695.75, y=22.10, z=370.45], EntityBat['Bat'/13145, l='MpServer', x=614.61, y=39.07, z=280.52], EntityBat['Bat'/14681, l='MpServer', x=691.66, y=21.83, z=372.02], EntitySheep['Sheep'/11354, l='MpServer', x=627.50, y=80.00, z=433.50], EntitySheep['Sheep'/353, l='MpServer', x=577.78, y=64.00, z=337.23], EntitySheep['Sheep'/355, l='MpServer', x=548.28, y=66.00, z=315.53], EntitySheep['Sheep'/356, l='MpServer', x=565.21, y=63.00, z=329.48], EntityItem['item.tile.emberEmitter'/14184, l='MpServer', x=563.99, y=64.00, z=337.54], EntityBat['Bat'/14441, l='MpServer', x=615.96, y=14.99, z=275.94], EntitySheep['Sheep'/11634, l='MpServer', x=695.27, y=68.00, z=404.52], EntitySheep['Sheep'/371, l='MpServer', x=613.50, y=64.00, z=336.50], EntitySheep['Sheep'/11635, l='MpServer', x=682.25, y=65.00, z=407.22], EntitySheep['Sheep'/372, l='MpServer', x=613.50, y=64.00, z=338.50], EntitySheep['Sheep'/11636, l='MpServer', x=683.98, y=65.00, z=408.10], EntitySheep['Sheep'/11124, l='MpServer', x=631.79, y=63.00, z=283.68], EntitySheep['Sheep'/11125, l='MpServer', x=636.86, y=63.00, z=285.18], EntitySheep['Sheep'/11637, l='MpServer', x=681.50, y=65.00, z=402.50], EntitySheep['Sheep'/11126, l='MpServer', x=639.84, y=63.00, z=280.85], EntityZombie['Zombie'/14710, l='MpServer', x=644.50, y=66.00, z=379.50], EntitySheep['Sheep'/11127, l='MpServer', x=629.50, y=63.00, z=291.50], EntitySheep['Sheep'/11128, l='MpServer', x=630.50, y=63.00, z=293.50], EntitySheep['Sheep'/11129, l='MpServer', x=629.50, y=63.00, z=294.50], EntitySheep['Sheep'/11385, l='MpServer', x=648.42, y=64.00, z=288.70], EntitySheep['Sheep'/11386, l='MpServer', x=645.31, y=63.00, z=275.24], EntityBat['Bat'/14460, l='MpServer', x=637.13, y=14.86, z=298.68], EntitySheep['Sheep'/11134, l='MpServer', x=628.56, y=64.00, z=341.77], EntitySheep['Sheep'/11135, l='MpServer', x=635.81, y=64.00, z=342.78], EntitySheep['Sheep'/11391, l='MpServer', x=654.50, y=63.00, z=340.50], EntitySheep['Sheep'/384, l='MpServer', x=625.26, y=64.00, z=331.43], EntitySheep['Sheep'/11392, l='MpServer', x=641.11, y=64.00, z=345.51], EntitySheep['Sheep'/11393, l='MpServer', x=653.23, y=64.00, z=355.17], EntitySheep['Sheep'/386, l='MpServer', x=614.50, y=64.00, z=324.76], EntitySkeleton['Skeleton'/14727, l='MpServer', x=566.50, y=64.00, z=307.50], EntityMinecartChest['Minecart with Chest'/397, l='MpServer', x=621.50, y=14.06, z=317.50], EntityBat['Bat'/13965, l='MpServer', x=583.51, y=20.05, z=300.03], EntityBat['Bat'/13970, l='MpServer', x=621.09, y=19.10, z=365.46], EntityMinecartChest['Minecart with Chest'/410, l='MpServer', x=603.50, y=15.06, z=285.50], EntityCreeper['Creeper'/14242, l='MpServer', x=561.50, y=65.00, z=293.50], EntityPig['Pig'/423, l='MpServer', x=584.50, y=63.00, z=284.50], EntityPig['Pig'/424, l='MpServer', x=584.50, y=63.00, z=284.50], EntityPig['Pig'/425, l='MpServer', x=584.50, y=63.00, z=285.50], EntityPig['Pig'/426, l='MpServer', x=585.50, y=64.00, z=286.50], EntitySheep['Sheep'/431, l='MpServer', x=543.70, y=65.00, z=333.80], EntityZombie['Zombie'/14255, l='MpServer', x=597.72, y=65.00, z=357.51], EntityBat['Bat'/13745, l='MpServer', x=571.65, y=16.89, z=378.38], EntityPlayerSP['The_corruption'/95, l='MpServer', x=617.68, y=66.31, z=356.95], EntitySpider['Spider'/14268, l='MpServer', x=572.00, y=68.00, z=417.85], EntitySkeleton['Skeleton'/12990, l='MpServer', x=606.22, y=64.00, z=340.32], EntityCreeper['Creeper'/14278, l='MpServer', x=629.28, y=68.00, z=388.70], EntitySkeleton['Skeleton'/14279, l='MpServer', x=668.50, y=63.00, z=365.50], EntityCreeper['Creeper'/14027, l='MpServer', x=588.50, y=19.00, z=409.50], EntitySheep['Sheep'/460, l='MpServer', x=593.58, y=68.00, z=397.28], EntityCreeper['Creeper'/14028, l='MpServer', x=590.50, y=19.00, z=408.50], EntitySheep['Sheep'/461, l='MpServer', x=597.61, y=64.41, z=389.86], EntitySheep['Sheep'/462, l='MpServer', x=598.12, y=64.40, z=392.79], EntitySheep['Sheep'/463, l='MpServer', x=596.88, y=64.20, z=393.97], EntityCreeper['Creeper'/14036, l='MpServer', x=650.51, y=64.00, z=276.83], EntityCreeper['Creeper'/14038, l='MpServer', x=653.50, y=64.00, z=284.50], EntitySpider['Spider'/13277, l='MpServer', x=594.50, y=65.00, z=292.50], EntityZombie['Zombie'/14558, l='MpServer', x=540.50, y=67.00, z=322.50], EntityZombie['Zombie'/14559, l='MpServer', x=540.50, y=67.00, z=318.50], EntitySkeleton['Skeleton'/14560, l='MpServer', x=539.50, y=67.00, z=318.50], EntitySpider['Spider'/13538, l='MpServer', x=543.01, y=68.00, z=303.01], EntitySpider['Spider'/13539, l='MpServer', x=553.09, y=66.00, z=303.91], EntitySpider['Spider'/13795, l='MpServer', x=647.50, y=63.00, z=297.50], EntityBat['Bat'/14055, l='MpServer', x=633.80, y=16.11, z=346.59], EntityZombie['Zombie'/13800, l='MpServer', x=643.50, y=63.00, z=300.50], EntityBat['Bat'/14057, l='MpServer', x=651.46, y=22.81, z=339.34], EntityZombie['Zombie'/14572, l='MpServer', x=611.50, y=77.00, z=429.50], EntityBat['Bat'/14066, l='MpServer', x=599.47, y=34.78, z=305.16], EntityBat['Bat'/14067, l='MpServer', x=592.98, y=34.07, z=299.38], EntityEnderman['Enderman'/13814, l='MpServer', x=590.50, y=68.00, z=410.50], EntitySkeleton['Skeleton'/13050, l='MpServer', x=598.50, y=34.00, z=298.50], EntitySkeleton['Skeleton'/14074, l='MpServer', x=602.50, y=37.00, z=287.50], EntityCreeper['Creeper'/13052, l='MpServer', x=596.50, y=34.00, z=298.50], EntityZombie['Zombie'/14078, l='MpServer', x=617.50, y=18.00, z=307.50]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:400)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 474140688 bytes (452 MB) / 2074607616 bytes (1978 MB) up to 5726797824 bytes (5461 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
    IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
    FML: MCP 9.32 Powered by Forge 12.18.1.2095 6 mods loaded, 6 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA    mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
    UCHIJAAAA    FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2095.jar)
    UCHIJAAAA    Forge{12.18.1.2095} [Minecraft Forge] (forge-1.10.2-12.18.1.2095.jar)
    UCHIJAAAA    embers{0.002} [Embers] (embers-0.002.jar)
    UCHIJAAAA    JEI{3.10.0.261} [Just Enough Items] (jei_1.10.2-3.10.0.261.jar)
    UCHIJAAAA    jeresources{0.5.1.56} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.1.56.jar)
    Loaded coremods (and transformers):
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1065.0' Renderer: 'AMD RADEON HD 6350'
    Launched Version: forge-12.18.1.2095
    LWJGL: 2.9.4
    OpenGL: AMD RADEON HD 6350 GL version 4.5.13399 Compatibility Profile Context 15.200.1065.0, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: Yes
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Packs:
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: 8x Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz

This happened when I placed a bunch of ember emitters branching from each other in creative over a lava pool, I'm using forge 12.18.1.2095.

**Comment by elucent** [comment]
I *think* this is fixed. Will upload a new version now.

**Comment by TheCorruption** [comment]
You said in the other issue and this one that you didn't know for sure this is fixed, I tried it again in 0.004 and there seems to be no problem, thank you.
