### ISSUE TITLE
Crash on using beam cannon

### ISSUE THREAD

**Issue by rotovap** [RootsTeam/Embers#60]
Minecraft crashes when activating beam cannon

[qMaRO.txt](https://github.com/RootsTeam/Embers/files/682449/qMaRO.txt)

**Comment by elucent** [comment]
I _think_ this is fixed now, I'll test it out and release a fixed build later today.

**Comment by elucent** [comment]
Yep, fixed! Also made the recipe checking code a _heck_ of a lot simpler.
