### ISSUE TITLE
Placing Ember Relay on top of Ember Activator crash.

### ISSUE THREAD

**Issue by wiloxe** [RootsTeam/Embers#61]
The title says it all pretty much. But more info is always good.
So it was not me who got this crash error but it was "xXxNeed4BloodxXx" since he's the only one who's messing around with Embers on the server at this moment. He sent me the crash report and had to go (Sleep) so i decided to post it here and if more info is required from him or me feel free to ask.
All i was told was "Placed Embers Relay on top of Ember Activator" With a link to the crash report.

Forge Version: 12.18.3.2202
Embers Version: 0.101
CrashLog: http://pastebin.com/q5tyheQ6

**Comment by LooneyMarauder** [comment]
I am also getting this crash. It seems to me the issue happens when I press shift with the hammer in my hand.

Resonant Rise (b1.0.1)
Pastebin `http://pastebin.com/AnGDpWhN`

**Comment by elucent** [comment]
Fixed this, I'll put together a released fix later today.
