### ISSUE TITLE
Swapping eye of the ancients

### ISSUE THREAD

**Issue by TheCorruption** [RootsTeam/Embers#62]
If you swap the eye of the ancients with another item in the inventory while holding the eye, it shows the eye being held instead of the item you're actually holding.
![2017-01-06_18 20 28](https://cloud.githubusercontent.com/assets/22695945/21744661/e1fa83b2-d4df-11e6-9da7-72fcdafceed7.png)

**Comment by elucent** [comment]
Should be fixed, uploading new version now.
