### ISSUE TITLE
Molten metals are called "fluid.molten_(metal)"

### ISSUE THREAD

**Issue by TheCorruption** [RootsTeam/Embers#63]
Also, they're called tile.null.name and have missing textures in JEI.
tested on 0.102.

**Comment by elucent** [comment]
Wait, really? This is the exact bug I thought I fixed...

It's not happening in the dev version at least, I'll see if I can figure anything out.

**Comment by elucent** [comment]
Oh, I just screwed up in a really stupid way. I'll get a fixed build out soon, but it'll be after I wrap up the first Roots 2 alpha build.
