### ISSUE TITLE
[1.10.2] All moltern metals removed??

### ISSUE THREAD

**Issue by b0bst3r** [RootsTeam/Embers#64]
embers-0.102

![untitled](https://cloud.githubusercontent.com/assets/2760085/21810416/9b56a59c-d743-11e6-9320-84e80b995b3b.png)

Is this related to https://github.com/RootsTeam/Embers/issues/63 ??

I don't really want to push an update that wipes out all your moltern metals.

**Comment by TheCorruption** [comment]
They were renamed, if you want to keep the molten metals in your world, don't use 0.102 and wait for the next update.

**Comment by elucent** [comment]
Yeah, I'll be updating shortly. It might still screw up the molten metals though. It's just the blocks that are getting changed though, so if they're in liquid form in tanks they should be fine.

**Comment by b0bst3r** [comment]
Metal blocks or all Ember blocks?

**Comment by b0bst3r** [comment]
This isn't fixed, getting the exact same thing in 0.103

**Comment by elucent** [comment]
Just the fluid metal blocks in-world. This update breaks them since their id itself was causing issues. I'm still a little confused about *why*, but it shouldn't affect any molten metals you have stored anywhere, just molten metals you've placed in the world.
