### ISSUE TITLE
Blazing Ray charge shot

### ISSUE THREAD

**Issue by VallenFrostweaver** [RootsTeam/Embers#65]
Currently I have no loss/gain of accuracy at any range with or without charging the Blazing Ray as stated by the Eye of the Ancients.

**Comment by elucent** [comment]
It's subtle. I might change it later to be more of an effect, but I don't want it to be annoying.

**Comment by elucent** [comment]
Meh, I'll just remove that line from the documentation. No need to make the Ray more annoying for no reason.
