### ISSUE TITLE
[Suggestion] Endless Ember Yield or Renewable Sources

### ISSUE THREAD

**Issue by Enderlook** [RootsTeam/Embers#66]
Please, make in the config the option to have an endless amount of ember yield. I love renewable resources. You could make:
A) Simply, make ember yield with endless amount of ember.
B) Ember yield can regen it ember in a slow rate (like 5% of maximum ember per hour or something similar [or also, it only regen in the day, or in full phase moon]).
C) Ember yield can get depleted, but randomly every minecraft day (or every 1-3 hours or something like that) it spawn an ember yield in randoms chunks (make a prefence in areas with low chunks with ember).

Also, if you don't like any of that ideas, please make ember yield compatible in mods dimentions, like Aroma1997s Dimensional World.

----------O---------

Also, I think some other ways of get ember: (I make "" descriptions to make more funny :))
* Ember ore: "The ember ore is a very rare material only found in the deepness of the world, this ore were created thousands of years ago, when yields of ember have too much energy by that time, it was concentrated, solidify and trapped in shards and crystals [(like amber (shard) and a bug (energy)], that are petrify in the deepness of the stone."
Notes: The ember veins are founded in quantities of 3-5, but are more rare than emeralds (but can spawn in every biome [one ember ore per 1-2 chunks, diamond is 3.097 per chunk]). Their are two ores: ember shard (most common) and ember crystal (rarest), the last can only be founded in large veins (5 blocks) where 1 block is that. Ember veins are in low levels (below Y=16, like diamond). It can be found in nether too (close to lava and deep).
I thought in ember ore like a early access to ember shards, because in late game their are too small to make someting.
* Ember crystals: "Ember crystals are only found in deep caves, their are founded in small clusters. Their were formed thousand of year ago, when the ember flewed by the air and not was trapped in the earth. This powerfull energy, when reached water or minerals crystals, it made a powerfull and slow reaction, the energy focus in the matter and cristalyzate this makings clusters of shards and crystals. Now, the are a wonderful and mystic thing, they can grow very slow, when their are closed to a yield..."
Notes: The ember crystal (not confuse with actually ember crystal) is founded in quantities of 1 cluster, or very rare 2-3 cluster, their are in caves. When their are near ember yield their can grow very slow (one shard every 15-45 minutes). When you broke a cluster, it drops 2-3 ember shards or 1 ember crystal. Also cristal have low luminosity (when their grow, the light also grow)
I based the crystal in thaumcraft farming crystal, you could make an item to farm the clusted without breaking it.
I thought in crystal like mid or late game farming system (early you haven't the right item to farm them, mid you can farm but not get more clusters, and late you can make an expensive "recipe" to craft clusters)
* Solar collector: "Ember shard are container of a powerfull energy, the ember. It is like the fire, a powerfull but raw energy, you can use this power to make or destroy, you own choise, now that we know how ember ore were formed, the right question is... ¿Where ember come from? Well, the ember, like all the energy and life of this world comes from the sun. The rays of light and heat that warm and bring life to the planet, also bring the fire energy, the ember, when the light -with ember- touch life, plants, their absorbs this powe, then, when animal eat that plants, this energy changes of vessel, and when their dies, ember goes to the soil and finally plant re-absobs it, if you think this over, it's cycle, but, if you think a bit more, this cycle always incorporate ember, never loose, how can it be possible? Well, if something have and input, also have and output, think in charcoal or oil, their where organic matter, but what happened, the matter was trapped by layers of dirt and stone, and these layers expel the matter to the cycle, and millions of year after that, the matter transforms it in charcoal and oil, well, with ember it's the same, the ember is trapped in ember yield in the deepnees of the earth, and thoundsands of thear after, it makes ember ore also. But, the final question is, ¿If we could absorbs the solar light before it is absorbed by life? This is the Solar collector, a machine than can absorb ember energy directly of the owner sun."
Notes: this expensive machine can produce ember energy with sun (if you need ember shards, a "Crystalizer" could be another machine [is the counterpart of ember activator, it produce shards with energy]).
I thought that this machine could be perfect for late game, a way to produce ember without move your base to another yield.
* Ember collector: "The nether, imbued of pure ember, it have the stongest ember yields, shards, ores and clusters. With so much energy, you could make a new machine: the ember collector, placing near lava, the blood of the nether, you can extract an endless (or almost endlees) amount of ember!"
Notes: this machine is similar to the solar collector, but it also works in night at cost of one thing, only work in the nether (and who wants lo live there?)...
* Ember absorber: "This new machine could be your best work, with an ember absorber, you can sacrifice items, like stone, coal, gold or diamond, or even meat [foot]. Every objet in the world have an small amount of ember to offer to this machine, ores have a very old energy, gained thounsands years ago, while meat, wheat, plant, and animals (mobs) has new energy, full of life and power. With this machine you can sacrifice item to get ember of them... but... ¿If you could make an ember sacrifice (mobs) ritual...?
Notes: this machine is simple, you put items, you get ember. To get a full list of ember value per item you could base in EMC of Alchemy mods, like Proyect E or something similar. The ritual could be a multiblock machine (like the most of your machines [but bigeer than 1x2 or 3x3x1]) and it extract the lifeforce (HP) of mobs to get ember.

Ah. Sorry for my english.

PD: If i put this post in a wrong place, sorry, it is my first time in Github, I just make an account to make this suggestion.

**Comment by elucent** [comment]
The entire point of Ember as a power system is for it to be limited. The limitation on how much Ember you can harvest promotes careful use of it, and also the relatively small capacity per chunk promotes multiple harvesting centers, or prospecting to find spikes of the stuff. Being able to simply generate Ember would make it much more like any other mod's power system, which I'd rather not do. I plan to add better means of refining Ember from its crystal form in the future, but the core mechanic of harvesting a limited resource from the earth will still apply, I won't be adding any renewable sources.

One caveat though, that you might like: with the latest few versions, Ember _will_ naturally regenerate in chunks. It's too slow to use for constant power, but if you run out of Ember in a chunk, it won't be gone forever. It'll just take a while to regenerate.

**Comment by Enderlook** [comment]
Thanks the answer.

**Comment by elucent** [comment]
For now, it's only in the overworld. I have a plan for the lore of Embers that effectively means that Ember only makes sense in the overworld, but if another mod added a dimension I thought Ember would have a place in, I could add support for it.
