### ISSUE TITLE
[Suggestion] Epic Tools/weapon placement

### ISSUE THREAD

**Issue by VallenFrostweaver** [RootsTeam/Embers#67]
I can't agree more with the public that the models of the Mantle Cartridge/Jar, both Clockwork tools, Cinder Staff, and Grandhammer are amazing pieces and look wonderful I can't help but also agree that the models do take up a large area of the screen (Blazing Ray is placed nicely though).  I noticed that Vanilla tools/weapons tend to have a slant back on 1st person view and perhaps this would help? Or, barring that, just edging them to the side a bit more?  Just a thought. 

I included a screen shot for comparison: http://imgur.com/a/9NOdH
![compare-picks](https://cloud.githubusercontent.com/assets/13642054/21887197/d614cb7c-d8b6-11e6-8e90-e94077c38567.png)

**Comment by elucent** [comment]
Sure, I can probably do that. This isn't the first time I've received the suggestion, someone else mentioned it a day or two ago, so I'll be sure to change this up in the near future when I next get a release out.

**Comment by elucent** [comment]
Eh, at this point, I'm just keeping them as they are. They've grown on me.

**Comment by VallenFrostweaver** [comment]
I thought you had moved them slightly some time ago?

**Comment by VallenFrostweaver** [comment]
Nvm. I'm a derp. That's why it's being closed. XD
