### ISSUE TITLE
Ashen Cloak and Inflictor Gem Duplication Bug

### ISSUE THREAD

**Issue by charlie-e09ae35d** [RootsTeam/Embers#68]
multimc 0.4.11-703
forge 12.18.3.2185
embers 0.103

When removing Inflictor Gems embedded in Ashen Cloak gems appear in crafting interface (2x2 or 3x3) as gem-free cloak is returned in crafting output, returned gems populate crafting array one after another starting from first slot (top row, left column), if cloak with gems was placed in slot that will not be overwritten with returning gems, cloak will stay in its place allowing for gem and cloak duplication.
Also, when embedding gems into cloak in stacks containing more than one gem, cloak stores stack size used, so when removing embedded gems it returns them in stacks used in crafting despite crafting process consuming only one gem per slot.

**Comment by elucent** [comment]
I know how to fix this now, I'll implement a fix in the near future.

**Comment by elucent** [comment]
Fixed!
