### ISSUE TITLE
Ashen Cloak Gem Removal in 2x2 Interface Crash

### ISSUE THREAD

**Issue by charlie-e09ae35d** [RootsTeam/Embers#69]
multimc 0.4.11-703
forge 12.18.3.2185
embers 0.103

Removing gems from a cloak containing more than four Inflictor Gems in a 2x2 crafting interface crashes client.

**Comment by elucent** [comment]
Should be an easy-enough fix. I'll get to it in the nearish future, though I'm focusing on Roots primarily at the moment.

**Comment by elucent** [comment]
Fixed!
