### ISSUE TITLE
Game Overlay Render Apparently

### ISSUE THREAD

**Issue by jsaggers** [RootsTeam/Embers#7]
HI, loving the mod so far.
I have this in a modpack with about 100 other mods, I placed a magic bean from random things and started to climb the bean shoot to the loot chest at the top and crash with the main mention being your mod.
[crash-2016-10-08_22.24.33-client.txt](https://github.com/RootsTeam/Embers/files/517641/crash-2016-10-08_22.24.33-client.txt)

I can't get back into the world so I created a knew world and I can't seem to reproduce this crash again.

**Comment by elucent** [comment]
Update Embers, I *think* I fixed this in 0.004. The other guy who reported this bug hasn't said anything about it since that version came out, so I assume I fixed it.
