### ISSUE TITLE
Research Table Hint Format Error with Ashen Cloak Item

### ISSUE THREAD

**Issue by charlie-e09ae35d** [RootsTeam/Embers#70]
multimc 0.4.11-703
forge 12.18.3.2185
embers 0.103

Percent sign in Ashen Cloak description should be escaped with "%" ("15%" should be "15%%"), otherwise description starts with "Format error: " string.

![bw2a0z7](https://cloud.githubusercontent.com/assets/13768838/21895052/9e0a8f2a-d8e1-11e6-8ec3-e54d041b72ca.png)

**Comment by elucent** [comment]
That's...weird. Easy enough fix.

**Comment by elucent** [comment]
Fixed.
