### ISSUE TITLE
Research Table Hopper Interactions Do Not Update Item Model in Research Table

### ISSUE THREAD

**Issue by charlie-e09ae35d** [RootsTeam/Embers#72]
multimc 0.4.11-703
forge 12.18.3.2185
embers 0.103

Either inputting items using hopper to sides of Research Table or removing them with hopper underneath does not update model currently displayed in Research Table.

**Comment by elucent** [comment]
Another easy-enough fix. Thanks for all the bug reports by the way, I'll work through these hopefully over the weekend when I have time (got exams at the moment, not the most time to devote to modding).

**Comment by elucent** [comment]
This should be fixed now. Expect a release with a fix soon.
