### ISSUE TITLE
[Suggestion] Acient Golem Drops

### ISSUE THREAD

**Issue by Enderlook** [RootsTeam/Embers#73]
Hi! After having killed a few golems, I have come to realize that they only drop Core Stone, so I decided to see a video to know if they drop something more, well, afte watch the guide I saw said that they also drop Eye of the Ancients. I think that they also could drop Ember Shard like a common drop and Ember Crystal like a rare drop (where they acquire ember to shot these firebalss?).
I am not very expert with this mod, but, I don't found any use for the Core Stone, Am I right? I don't understand alchemy yet...

**Comment by elucent** [comment]
The Core Stone isn't used yet, though I have some uses planned for it in the future. I don't want the golems to drop Ember shards or Ember crystals because I don't want them to be farmable in mob farms, thus giving the player renewable sources of Ember power.
