### ISSUE TITLE
Clockwork tools and grandhammer still can't be enchanted in 1.10.2 v0.104

### ISSUE THREAD

**Issue by the-realest-stu** [RootsTeam/Embers#75]
changelog says they can, but they can't

**Comment by elucent** [comment]
Oh, whoops, I forgot to backport that change to 1.10.2.

**Comment by elucent** [comment]
Eh. My official policy at this point is to keep my development on 1.11.2 unless there's something truly gamebreaking on 1.10.2. I'm going to stick to this.
