### ISSUE TITLE
Item Pipes Do Not Connect to Item Dropper on Its Top Side

### ISSUE THREAD

**Issue by charlie-e09ae35d** [RootsTeam/Embers#76]
multimc 0.5.0-871
minecraft 1.10.2
forge 12.18.3.2185
embers 0.104

![item_pipe_item_dropper](https://cloud.githubusercontent.com/assets/13768838/22062534/85aad500-dd7a-11e6-91ec-226ac261ffff.png)

**Comment by elucent** [comment]
Should be fixed.
