### ISSUE TITLE
Copper Charger Description Discrepancies

### ISSUE THREAD

**Issue by charlie-e09ae35d** [RootsTeam/Embers#78]
multimc 0.5.0-871
minecraft 1.10.2
forge 12.18.3.2185
embers 0.104

When looking at Copper Charger with an Eye of the Ancients:
- title is Charger instead of Copper Charger
- description references Ember Cartridge and Ember Jar but item names are Mantle Cartridge and Mantle Jar

**Comment by elucent** [comment]
Fixed.
