### ISSUE TITLE
Melter Does Not Process Blocks of Metal, Metal Plates

### ISSUE THREAD

**Issue by charlie-e09ae35d** [RootsTeam/Embers#79]
multimc 0.5.0-871
minecraft 1.10.2
forge 12.18.3.2185
embers 0.104

Inconsistency, it can process metal nuggets and ingots.

**Comment by elucent** [comment]
I'll add the plates, but the blocks of metal are too big to be melted down. I didn't want people crafting metal blocks to get more efficient melting -- it doesn't make sense realistically.

**Comment by charlie-e09ae35d** [comment]
I didnt notice processing any item in Melter takes the same amount of time/ember. Melter has enough capacity to fit molten metal block worth of fluid and it can already melt item size of a block (ore blocks).

Making time and ember cost be dependant of item output would be neat. Not an issue though.

**Comment by elucent** [comment]
Added plate recipes. I may or may not add block recipes in the future, not sure yet.
