### ISSUE TITLE
Ember Emitter Does Not Visually Connect to Button Placed on It

### ISSUE THREAD

**Issue by charlie-e09ae35d** [RootsTeam/Embers#80]
multimc 0.5.0-871
minecraft 1.10.2
forge 12.18.3.2185
embers 0.104

It does for a lever.
![emiter_buttons](https://cloud.githubusercontent.com/assets/13768838/22062970/b1767138-dd7c-11e6-9295-e14fa2543d44.png)

**Comment by elucent** [comment]
I can add this, but I do have to ask: why would you ever want to use a button for this? It's kinda really impractical.

**Comment by charlie-e09ae35d** [comment]
Just for consistency sake, it is of very low importance.

**Comment by elucent** [comment]
Fixed.
