### ISSUE TITLE
Stamper Accepts Stamps in Stacks Larger Than One Item, Returns Always One When Removed by Hand

### ISSUE THREAD

**Issue by charlie-e09ae35d** [RootsTeam/Embers#81]
multimc 0.5.0-871
minecraft 1.10.2
forge 12.18.3.2185
embers 0.104

Right clicking Stamper with stamps in stack size larger than one will delete all but one stamp.
Inputting via hopper will return (on right click) proper stack size of inserted stamps.

**Comment by elucent** [comment]
Fixed!
