### ISSUE TITLE
Cannot Create Ash Pile from Alchemical Waste

### ISSUE THREAD

**Issue by charlie-e09ae35d** [RootsTeam/Embers#82]
multimc 0.5.0-871
minecraft 1.10.2
forge 12.18.3.2185
embers 0.104

Same Stamper - Stamp Base set up works with metal plates and ingots (after stamp replacement and molten metal access).
Alchemical Waste was produced and not spawned through JEI.
Multiple Alchemical Waste "Accuracy" values were tested.
Stamp Base had no molten metal inside.

![stamper_waste_ash](https://cloud.githubusercontent.com/assets/13768838/22063265/380fe8d6-dd7e-11e6-9a0e-bdf147fc1ef9.png)

**Comment by elucent** [comment]
Fixed.
