### ISSUE TITLE
Unrecoverable Crash with Ember Relays Connected in a Loop

### ISSUE THREAD

**Issue by charlie-e09ae35d** [RootsTeam/Embers#84]
multimc 0.5.0-871
minecraft 1.10.2
forge 12.18.3.2185
embers 0.104

Activating ember transfer with relays connected in a closed loop crashes client and makes world unloadable.

[mc_1.10.2_embers_0.104_relays_coop_crash.log](https://gist.github.com/charlie-e09ae35d/a57211549d000883e6a050d8f78a3f3a)

![mc_1 10 2_embers_0 104_relays_coop_crash](https://cloud.githubusercontent.com/assets/13768838/22063599/e36592b6-dd7f-11e6-9af6-5d6f23563daa.png)

**Comment by elucent** [comment]
Fixed.
