### ISSUE TITLE
Beam Cannon Activation Inconsistencies

### ISSUE THREAD

**Issue by charlie-e09ae35d** [RootsTeam/Embers#85]
multimc 0.5.0-871
minecraft 1.10.2
forge 12.18.3.2185
embers 0.104

Does not respond to redstone signal immediately.
Cannot be activated reliably with a signal from single button push (can be if button is spam clicked).
Activation with redstone signal is dependent on signal duration (the longer the signal the more probable activation is, ~8-12 seconds, no longer than 20).
Responds to redstone dust only when connected via straight connection and not at all with elbow, T, cross connection.

**Comment by elucent** [comment]
The redstone is a toggle, not an activator. Toggling the device just means that the next time it prepares a shot, it'll actually shoot something -- not that the cannon will instantly fire. Responding to a straight connection of redstone only is also standard vanilla behavior -- try a similar setup with a piston.

**Comment by charlie-e09ae35d** [comment]
Pistons do not indicate direct connection when redstone dust is not pointed at them, thats why i would not expect them to activate.
![pistons-canon-redstone](https://cloud.githubusercontent.com/assets/13768838/22073619/0d4876b8-dda6-11e6-92b3-614c331d318e.png)

**Comment by charlie-e09ae35d** [comment]
Sorry, could I get a confirmation that this situation is completely intended behaviour?
- Beam Cannon internal buffer is fully loaded (2000/2000 ember, shot fully prepared).
- Redstone signal is applied.
- Cannon does not shoot immediately, few seconds (on average) has to pass for it to shoot its beam.

**Comment by elucent** [comment]
Yes, that's as intended. I can probably change the powering situation.
