### ISSUE TITLE
Crystal Cell Capacity Increase Description Error

### ISSUE THREAD

**Issue by charlie-e09ae35d** [RootsTeam/Embers#86]
multimc 0.5.0-871
minecraft 1.10.2
forge 12.18.3.2185
embers 0.104

When looking at Crystal Cell with Eye of the Ancients it states that:
"...Eight Ember crystals or 48 Ember shards, or some mixture, will bring the cell to full capacity..."
One Ember Crystal adds 90k, Ember Shard adds 15k to maximum capacity of 1440k, cell starts with 64k. To attain maximum capacity (with minimal ember loss) Crystal Cell needs to be fed 16 Ember Crystals or 92 Ember Shards.

**Comment by elucent** [comment]
I believe I nerfed this and forgot to update the documentation. Considering that the documentation is pending a rewrite anyway, I'll likely save this fix for then.

**Comment by elucent** [comment]
Fixed.
