### ISSUE TITLE
Ember Tools Held in Offhand Do Not Update in First Person View After Replacing Them

### ISSUE THREAD

**Issue by charlie-e09ae35d** [RootsTeam/Embers#87]
multimc 0.5.0-871
minecraft 1.10.2
forge 12.18.3.2185
embers 0.104

Once placed in offhand any ember consuming tool model will stay in offhand despite being replaced with any other item.
Model can be removed only manually via dragging out of offhand slot or by highlighting empty slot in toolbar and pressing "F" key.

**Comment by elucent** [comment]
This should be fixed.
