### ISSUE TITLE
Chest Cannot Be Accessed by Player with Item Pump Connected on Its Top Side

### ISSUE THREAD

**Issue by charlie-e09ae35d** [RootsTeam/Embers#88]
multimc 0.5.0-871
minecraft 1.10.2
forge 12.18.3.2185
embers 0.104

Can with Item Pipe placed on top side.

**Comment by elucent** [comment]
Pumps are considered solid blocks. I think I might have to leave it like this -- unfortunately, if I make them unsolid, they'll lose the ability to have levers placed on them.
