### ISSUE TITLE
Mantle Cartridge Is Not Recognised as Ember Source for Ember Consuming Tools While Not in Offhand

### ISSUE THREAD

**Issue by charlie-e09ae35d** [RootsTeam/Embers#89]
multimc 0.5.0-871
minecraft 1.10.2
forge 12.18.3.2185
embers 0.104

Mantle Jar can be used while being anywhere in players inventory (main inventory, toolbar, offhand).
Mantle Cartridge was crafted and charged manually.

**Comment by elucent** [comment]
This is intentional behavior. The point of the cartridge is to give you more Ember capacity if you sacrifice your offhand slot for it.
