### ISSUE TITLE
Suggestion: Caminite Lever

### ISSUE THREAD

**Issue by Hjaldar** [RootsTeam/Embers#9]
Just watched your dev spotlight. The mod looks amazing but those vanilla levers really look ugly stuck on your pipes. I'd suggest adding a Caminite Lever made using a stick and some form of caminite. I'd probably give it a square base rather than the rectangular one the vanilla lever has.

**Comment by elucent** [comment]
Eh, I think vanilla levers look fine, I might add a Caminite Lever but it would come whenever I get to a solid decorative-blocks update.

**Comment by Hjaldar** [comment]
Cool, thanks for considering my suggestion.

**Comment by laserlemons** [comment]
I second the idea of a cooler looking way to give redstone signal. The vanilla levers look too plain.

**Comment by Xakorik** [comment]
Agreed, it will match the feel of the mod better.

**Comment by elucent** [comment]
I wouldn't go with just Caminite though, it needs to stand out a bit from the material of the pumps.

**Comment by Alsender** [comment]
Perhaps an iron plated lever? Or maybe the caminite lever requires some gold nuggets for a bit of extra flash?

**Comment by charlesbevans** [comment]
Ask around, maybe you can get a mod like ArchitectureCraft to add a skinnable lever, or at least some variants.

**Comment by elucent** [comment]
Closing this, Embers content is on a pause right now, and I'm prioritizing new content over small stuff like this.
