### ISSUE TITLE
Item Gauge Issues with Vanilla Containers

### ISSUE THREAD

**Issue by charlie-e09ae35d** [RootsTeam/Embers#90]
multimc 0.5.0-871
minecraft 1.10.2
forge 12.18.3.2185
embers 0.104

Item Gauge on vanilla containers does not work
- displays slots of attached inventory
- does not display content of those slots
- tested on hopper, chest, trapped chest, dropper, dispenser, furnace

Tooltip of containers with more than five slots covers players toolbar and goes offscreen on some ui scale settings and inventory sizes.

**Comment by elucent** [comment]
I'm probably just going to remove the item gauge in its entirety. It's not very useful.
