### ISSUE TITLE
Mechanical Pump Vertical Connectors Issues

### ISSUE THREAD

**Issue by charlie-e09ae35d** [RootsTeam/Embers#91]
multimc 0.5.0-871
minecraft 1.10.2
forge 12.18.3.2185
embers 0.104

Cannot disable Mechanical Pump top connector to bottom side of Fluid Vessel.
Disabling bottom connector will disable top connector, both visually and functionally.

Disabling bottom connector with lever attached to top connector will disable both top and bottom visually but lever will function correctly.
![mechanical_pump_lever](https://cloud.githubusercontent.com/assets/13768838/22064441/e84f2a18-dd83-11e6-921d-d53a26567646.png)

**Comment by elucent** [comment]
Fixed.
