### ISSUE TITLE
Crash caused by item pump connected to active ember bore

### ISSUE THREAD

**Issue by Yenwodyah** [RootsTeam/Embers#92]
Minecraft 1.11.2
Minecraft Forge 13.20.0.2223
Embers 0.104

This setup causes a crash when the lever is activated:

![2017-01-19_23 30 09](https://cloud.githubusercontent.com/assets/25239573/22137256/8da92aec-de9f-11e6-99de-0d95d0018b2c.png)
The crash only occurs after fuel is added to the bore. The hopper is feeding in coal.

Crash report:

---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 1/19/17 11:30 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraftforge.items.ItemStackHandler.insertItem(ItemStackHandler.java:83)
	at teamroots.embers.tileentity.TileEntityItemPump.func_73660_a(TileEntityItemPump.java:395)
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.items.ItemStackHandler.insertItem(ItemStackHandler.java:83)
	at teamroots.embers.tileentity.TileEntityItemPump.func_73660_a(TileEntityItemPump.java:395)

-- Block entity being ticked --
Details:
	Name: embers:tile_entity_item_pump // teamroots.embers.tileentity.TileEntityItemPump
	Block type: ID #256 (tile.item_pump // teamroots.embers.block.BlockItemPump)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-191,4,63), Chunk: (at 1,0,15 in -12,3; contains blocks -192,0,48 to -177,255,63), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #256 (tile.item_pump // teamroots.embers.block.BlockItemPump)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1801)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: EmbersCrashTest
	All players: 1 total; [EntityPlayerMP['Yenwodyah'/912, l='EmbersCrashTest', x=-189.59, y=4.00, z=62.01]]
	Chunk stats: ServerChunkCache: 316 Drop: 0
	Level seed: -3540564552288952292
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-184,64,72), Chunk: (at 8,4,8 in -12,4; contains blocks -192,0,64 to -177,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2468 game time, 2468 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 140183 (now: false), thunder time: 63546 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 275584424 bytes (262 MB) / 628559872 bytes (599 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 5, allocated: 17, tallocated: 89
	FML: MCP 9.38 Powered by Forge 13.20.0.2223 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2223.jar) 
	UCHIJAAAA	forge{13.20.0.2223} [Minecraft Forge] (forge-1.11.2-13.20.0.2223.jar) 
	UCHIJAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.jar) 
	UCHIJAAAA	embers{0.104} [Embers] (embers-0.104.jar) 
	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Yenwodyah'/912, l='EmbersCrashTest', x=-189.59, y=4.00, z=62.01]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by sargunster** [comment]
Can confirm. Getting this crash on MC 1.11.2 Embers 0.104. Crashes the server every time the player near the bore logs in. Had to go into MCEdit and delete the bore setup so the player could join again.

**Comment by elucent** [comment]
Fixed this now. Expect a release soon.
