### ISSUE TITLE
Crash happens when trying to mine stone type blocks with Grandhammer

### ISSUE THREAD

**Issue by MahnoGK** [RootsTeam/Embers#94]
Crash happens when trying to mine stone type blocks with Grandhammer:

**---- Minecraft Crash Report ----**

WARNING: coremods are present:
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.1.jar)
  CorePlugin (FluxedRedstone-2.6.0.54.jar)
  LoadingPlugin (ChunkAnimator-MC1.11-1.2.jar)
  RebornCoreASM (RebornCore-1.11.2-2.13.1.25-universal.jar)
  LoadingPlugin (Quark-r1.2-74.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 1/20/17 11:19 AM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.item.ItemTool.getHarvestLevel(ItemTool.java:129)
	at teamroots.embers.item.ItemGrandhammer.canHarvestBlock(ItemGrandhammer.java:131)
	at net.minecraft.item.ItemStack.func_150998_b(ItemStack.java:349)
	at net.minecraft.entity.player.InventoryPlayer.func_184432_b(InventoryPlayer.java:678)
	at net.minecraft.entity.player.EntityPlayer.func_184823_b(EntityPlayer.java:877)
	at net.minecraftforge.common.ForgeHooks.canHarvestBlock(ForgeHooks.java:172)
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:201)
	at net.minecraft.block.Block.func_180647_a(Block.java:545)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:412)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:240)
	at PlayerControllerOF.func_180511_b(PlayerControllerOF.java:42)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1460)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2174)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at  #sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.item.ItemTool.getHarvestLevel(ItemTool.java:129)
	at teamroots.embers.item.ItemGrandhammer.canHarvestBlock(ItemGrandhammer.java:131)
	at net.minecraft.item.ItemStack.func_150998_b(ItemStack.java:349)
	at net.minecraft.entity.player.InventoryPlayer.func_184432_b(InventoryPlayer.java:678)
	at net.minecraft.entity.player.EntityPlayer.func_184823_b(EntityPlayer.java:877)
	at net.minecraftforge.common.ForgeHooks.canHarvestBlock(ForgeHooks.java:172)
	at net.minecraftforge.common.ForgeHooks.blockStrength(ForgeHooks.java:201)
	at net.minecraft.block.Block.func_180647_a(Block.java:545)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185903_a(BlockStateContainer.java:412)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:240)
	at PlayerControllerOF.func_180511_b(PlayerControllerOF.java:42)
	at net.minecraft.client.Minecraft.func_147116_af(Minecraft.java:1460)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2174)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['MakhnoGK'/1071, l='MpServer', x=92.30, y=63.00, z=367.68]]
	Chunk stats: MultiplayerChunkCache: 266, 266
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (92,64,256), Chunk: (at 12,4,0 in 5,16; contains blocks 80,0,256 to 95,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 9836 game time, 9836 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 65 total; [EntityItem['item.item.egg'/8484, l='MpServer', x=96.13, y=66.00, z=326.47], EntityItem['item.item.ma.tier1_inferium_seeds'/8555, l='MpServer', x=82.23, y=68.00, z=332.39], EntityItem['item.item.ma.tier1_inferium_seeds'/8595, l='MpServer', x=84.00, y=68.00, z=335.38], EntityPig['Pig'/443, l='MpServer', x=39.50, y=63.00, z=310.50], EntityItem['item.item.ma.tier1_inferium_seeds'/8635, l='MpServer', x=82.99, y=68.00, z=335.88], EntityPig['Pig'/444, l='MpServer', x=38.50, y=63.00, z=310.50], EntityPig['Pig'/445, l='MpServer', x=27.48, y=66.00, z=308.25], EntityItem['item.item.ma.tier1_inferium_seeds'/8637, l='MpServer', x=84.79, y=68.00, z=336.72], EntityPig['Pig'/455, l='MpServer', x=50.50, y=69.00, z=295.50], EntityPig['Pig'/456, l='MpServer', x=48.50, y=69.00, z=295.50], EntityPig['Pig'/457, l='MpServer', x=46.50, y=69.00, z=294.50], EntityPig['Pig'/458, l='MpServer', x=46.50, y=69.00, z=294.50], EntityPig['Pig'/467, l='MpServer', x=25.50, y=98.00, z=406.50], EntityPig['Pig'/468, l='MpServer', x=24.50, y=97.00, z=402.50], EntityPig['Pig'/469, l='MpServer', x=24.50, y=97.00, z=402.50], EntityPig['Pig'/470, l='MpServer', x=24.50, y=98.00, z=406.50], EntityAuspiciousPoint['entity.auspicious_point.name'/477, l='MpServer', x=47.00, y=85.00, z=390.00], EntityChicken['Chicken'/482, l='MpServer', x=73.50, y=71.00, z=321.88], EntityChicken['Chicken'/483, l='MpServer', x=82.57, y=68.00, z=319.79], EntityChicken['Chicken'/484, l='MpServer', x=101.26, y=63.00, z=294.91], EntityChicken['Chicken'/485, l='MpServer', x=83.86, y=68.00, z=333.37], EntityItem['item.item.ma.tier1_inferium_seeds'/8691, l='MpServer', x=92.01, y=68.00, z=340.34], EntityPig['Pig'/723, l='MpServer', x=113.50, y=64.00, z=409.50], EntityPig['Pig'/724, l='MpServer', x=109.50, y=67.00, z=412.50], EntityPig['Pig'/725, l='MpServer', x=112.51, y=66.00, z=417.30], EntityPig['Pig'/726, l='MpServer', x=113.50, y=66.00, z=417.50], EntityDeer['Deer'/727, l='MpServer', x=132.91, y=64.00, z=308.07], EntityPig['Pig'/728, l='MpServer', x=138.32, y=64.00, z=353.81], EntityPig['Pig'/729, l='MpServer', x=130.88, y=66.00, z=358.17], EntityPig['Pig'/730, l='MpServer', x=132.46, y=65.00, z=356.78], EntityPig['Pig'/731, l='MpServer', x=130.70, y=67.02, z=360.51], EntityPig['Pig'/747, l='MpServer', x=158.50, y=63.00, z=339.50], EntityPig['Pig'/748, l='MpServer', x=160.50, y=63.00, z=337.50], EntityPig['Pig'/749, l='MpServer', x=158.50, y=63.00, z=336.50], EntityPig['Pig'/750, l='MpServer', x=154.50, y=63.00, z=337.50], EntityPig['Pig'/751, l='MpServer', x=154.50, y=69.00, z=420.50], EntityPig['Pig'/752, l='MpServer', x=154.50, y=68.00, z=418.50], EntityPig['Pig'/753, l='MpServer', x=155.50, y=69.00, z=420.50], EntityPig['Pig'/754, l='MpServer', x=156.50, y=69.00, z=419.50], EntityChicken['Chicken'/755, l='MpServer', x=161.50, y=70.00, z=414.50], EntityChicken['Chicken'/756, l='MpServer', x=159.50, y=69.00, z=415.50], EntityChicken['Chicken'/757, l='MpServer', x=156.50, y=68.00, z=414.50], EntityChicken['Chicken'/758, l='MpServer', x=154.50, y=68.00, z=417.50], EntitySquid['Squid'/9367, l='MpServer', x=114.02, y=62.35, z=381.69], EntitySquid['Squid'/9368, l='MpServer', x=108.49, y=60.00, z=379.65], EntitySquid['Squid'/9369, l='MpServer', x=102.34, y=62.50, z=378.60], EntitySquid['Squid'/9370, l='MpServer', x=108.03, y=62.59, z=371.95], EntitySkeleton['Skeleton'/9436, l='MpServer', x=74.50, y=52.00, z=405.50], EntityCreeper['Creeper'/9445, l='MpServer', x=17.50, y=54.00, z=288.50], EntityCreeper['Creeper'/9446, l='MpServer', x=17.50, y=54.00, z=289.50], EntityZombie['Zombie'/9521, l='MpServer', x=119.28, y=30.00, z=312.50], EntityCreeper['Creeper'/9524, l='MpServer', x=121.50, y=28.00, z=296.50], EntityItem['item.item.egg'/9593, l='MpServer', x=73.03, y=71.00, z=322.32], EntityPlayerSP['MakhnoGK'/1071, l='MpServer', x=92.30, y=63.00, z=367.68], EntityZombie['Zombie'/9678, l='MpServer', x=55.50, y=61.00, z=393.50], EntityZombie['Zombie'/9679, l='MpServer', x=54.50, y=61.00, z=392.50], EntitySkeleton['Skeleton'/9815, l='MpServer', x=94.50, y=14.00, z=386.50], EntityBat['Bat'/9975, l='MpServer', x=13.97, y=18.99, z=301.42], EntityPig['Pig'/5940, l='MpServer', x=101.96, y=64.00, z=444.81], EntityPig['Pig'/5941, l='MpServer', x=99.89, y=64.00, z=443.45], EntityPig['Pig'/5942, l='MpServer', x=98.90, y=64.00, z=443.41], EntityPig['Pig'/5943, l='MpServer', x=100.50, y=66.00, z=440.50], EntitySkeleton['Skeleton'/10113, l='MpServer', x=122.48, y=26.00, z=292.29], EntityCreeper['Creeper'/10181, l='MpServer', x=168.50, y=25.00, z=446.50], EntityZombie['Zombie'/10229, l='MpServer', x=73.50, y=48.00, z=424.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1233695632 bytes (1176 MB) / 2656567296 bytes (2533 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2222 Optifine OptiFine_1.11.2_HD_U_B6 49 mods loaded, 49 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2222.jar) 
	UCHIJAAAA	forge{13.20.0.2222} [Minecraft Forge] (forge-1.11.2-13.20.0.2222.jar) 
	UCHIJAAAA	actuallyadditions{1.11.2-r96} [Actually Additions] (ActuallyAdditions-1.11.2-r96.jar) 
	UCHIJAAAA	adobeblocks{7.0.1} [Adobe Blocks 2] (AdobeBlocks-1.11.2-7.0.1.jar) 
	UCHIJAAAA	morphtool{1.1-13} [Morph-o-Tool] (Morph-o-Tool-1.1-13.jar) 
	UCHIJAAAA	psi{r1.1-44} [Psi] (Psi-r1.1-44.jar) 
	UCHIJAAAA	quark{r1.2-74} [Quark] (Quark-r1.2-74.jar) 
	UCHIJAAAA	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHIJAAAA	bdlib{1.13.1.3} [BD Lib] (bdlib-1.13.1.3-mc1.11.2.jar) 
	UCHIJAAAA	betterbuilderswands{0.11.0} [Better Builder's Wands] (BetterBuildersWands-1.11-0.11.0.233+4d933ac.jar) 
	UCHIJAAAA	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UCHIJAAAA	chunkanimator{1.2} [Chunk Animator] (ChunkAnimator-MC1.11-1.2.jar) 
	UCHIJAAAA	cyclicmagic{1.0.0} [Cyclic] (Cyclic-1.11.2-1.0.0.jar) 
	UCHIJAAAA	forestry{5.3.0.26} [Forestry] (forestry_1.11.2-5.3.0.26.jar) 
	UCHIJAAAA	eleccore{1.6.381} [ElecCore] (ElecCore-1.11-1.6.381.jar) 
	UCHIJAAAA	deepresonance{1.4.3} [DeepResonance] (deepresonance-1.1x-1.4.3.jar) 
	UCHIJAAAA	embers{0.104} [Embers] (embers-0.104.jar) 
	UCHIJAAAA	shetiphiancore{3.4.1} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.1.jar) 
	UCHIJAAAA	endertanks{1.5.1} [EnderTanks] (endertanks-1.11.0-1.5.1.jar) 
	UCHIJAAAA	valkyrielib{1.11.2-0.11.0b} [Valkyrie Lib] (valkyrielib-1.11.2-0.11.0b.jar) 
	UCHIJAAAA	environmentaltech{1.11.2-0.11.0b} [Environmental Tech] (environmentaltech-1.11.2-0.11.0b.jar) 
	UCHIJAAAA	reborncore{2.13.1.25} [RebornCore] (RebornCore-1.11.2-2.13.1.25-universal.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.13.1.25} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.13.1.25-universal.jar) 
	UCHIJAAAA	fluxedredstone{@MODVERSION@} [FluxedRedstone] (FluxedRedstone-2.6.0.54.jar) 
	UCHIJAAAA	gendustry{1.6.5.3} [GenDustry] (gendustry-1.6.5.3-mc1.11.2.jar) 
	UCHIJAAAA	pressure{1.3.1.3} [Pressure Pipes] (pressure-1.3.1.3-mc1.11.2.jar) 
	UCHIJAAAA	advgenerators{0.9.20.2} [Advanced Generators] (generators-0.9.20.2-mc1.11.2.jar) 
	UCHIJAAAA	jei{4.2.4.226} [Just Enough Items] (jei_1.11.2-4.2.4.226.jar) 
	UCHIJAAAA	techreborn{2.1.1.42} [TechReborn] (TechReborn-1.11.2-2.1.1.42-universal.jar) 
	UCHIJAAAA	hammerz{1.11.2-0.1.4.27} [Hammerz] (hammerz-1.11.2-0.1.4.27.jar) 
	UCHIJAAAA	jeibees{0.9.0.3} [JEI Bees] (jeibees-0.9.0.3-mc1.11.2.jar) 
	UCHIJAAAA	journeymap{1.11.2-5.4.4} [JourneyMap] (journeymap-1.11.2-5.4.4.jar) 
	UCHIJAAAA	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	UCHIJAAAA	minecolonies{1.11-0.6.2306} [MineColonies] (minecolonies-universal-1.11-0.6.2306.jar) 
	UCHIJAAAA	mousetweaks{2.7.1} [Mouse Tweaks] (MouseTweaks-2.7.1-mc1.11.2.jar) 
	UCHIJAAAA	mysticalagriculture{1.3.9} [Mystical Agriculture] (mysticalagriculture[1.11]-1.3.9.jar) 
	UCHIJAAAA	harvestcraft{1.11.2a} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2a.jar) 
	UCHIJAAAA	refinedstorage{1.3.5} [Refined Storage] (refinedstorage-1.3.5.jar) 
	UCHIJAAAA	rftools{5.81} [RFTools] (rftools-1.1x-5.81.jar) 
	UCHIJAAAA	rftoolscontrol{1.6.4} [RFTools Control] (rftoolsctrl-1.1x-1.6.4.jar) 
	UCHIJAAAA	rftoolsdim{4.53} [RFTools Dimensions] (rftoolsdim-1.1x-4.53.jar) 
	UCHIJAAAA	roguelike{1.6.2} [Roguelike Dungeons] (RoguelikeDungeons-1.11.2-1.6.2.jar) 
	UCHIJAAAA	roots{0.007} [Roots 2] (roots-2-0.007.jar) 
	UCHIJAAAA	storagedrawers{1.11.2-4.1.0} [Storage Drawers] (StorageDrawers-1.11.2-4.1.0.jar) 
	UCHIJAAAA	terraqueous{1.3.4} [Terraqueous] (terraqueous-1.11.0-1.3.4.jar) 
	UCHIJAAAA	unifieditems{1.4.5.129} [Unified Items] (UnifiedItems-1.11.2-1.4.5-129.jar) 
	UCHIJAAAA	usefulnullifiers{1.3.2} [Useful Nullifiers] (usefulnullifiers-1.3.2.jar) 
	Loaded coremods (and transformers): 
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.1.jar)
  shetiphian.core.asm.ClassTransformer
CorePlugin (FluxedRedstone-2.6.0.54.jar)
  
LoadingPlugin (ChunkAnimator-MC1.11-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
RebornCoreASM (RebornCore-1.11.2-2.13.1.25-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
LoadingPlugin (Quark-r1.2-74.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.54' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	List of loaded APIs: 
		* actuallyadditionsapi (32) from ActuallyAdditions-1.11.2-r96.jar
		* CoFHAPI (1.8.9R1.2.0B1) from FluxedRedstone-2.6.0.54.jar
		* CoFHAPI|energy (1.8.9R1.2.0B1) from FluxedRedstone-2.6.0.54.jar
		* CoFHAPI|item (1.8.9R1.2.0B1) from mcjtylib-1.1x-2.3.4.jar
		* compatlayer (0.1.7) from compatlayer-1.11.2-0.1.7.jar
		* DR-API (1.0.4-Beta) from deepresonance-1.1x-1.4.3.jar
		* ElecCoreAPI (1.0) from ElecCore-1.11-1.6.381.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.11-1.6.381.jar
		* environmentaltech-api (1.11.2-0.11.0b) from environmentaltech-1.11.2-0.11.0b.jar
		* ForestryAPI|apiculture (5.0.0) from forestry_1.11.2-5.3.0.26.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.11.2-5.3.0.26.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.11.2-5.3.0.26.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.11.2-5.3.0.26.jar
		* ForestryAPI|core (5.1.0) from forestry_1.11.2-5.3.0.26.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.11.2-5.3.0.26.jar
		* ForestryAPI|food (1.1.0) from forestry_1.11.2-5.3.0.26.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.11.2-5.3.0.26.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.11.2-5.3.0.26.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.11.2-5.3.0.26.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.11.2-5.3.0.26.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.11.2-5.3.0.26.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.11.2-5.3.0.26.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.11.2-5.3.0.26.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.11.2-5.3.0.26.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.11.2-5.3.0.26.jar
		* ForestryAPI|world (2.1.0) from forestry_1.11.2-5.3.0.26.jar
		* gendustryAPI (2.3.0) from gendustry-1.6.5.3-mc1.11.2.jar
		* jeresources|API (0.6.2.104) from JustEnoughResources-1.11.2-0.6.2.104.jar
		* journeymap|client-api (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* journeymap|client-api-display (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* journeymap|client-api-event (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* journeymap|client-api-model (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* journeymap|client-api-util (1.3-SNAPSHOT) from journeymap-1.11.2-5.4.4.jar
		* JustEnoughItemsAPI (4.11.0) from jei_1.11.2-4.2.4.226.jar
		* mcjtylib_ng (2.3.4) from mcjtylib-1.1x-2.3.4.jar
		* pressureAPI (1.3.1.3) from pressure-1.3.1.3-mc1.11.2.jar
		* PsiAPI (3) from Psi-r1.1-44.jar
		* reborncoreAPI (2.13.1.25) from RebornCore-1.11.2-2.13.1.25-universal.jar
		* reborncoreAPI|Fuel (2.13.1.25) from RebornCore-1.11.2-2.13.1.25-universal.jar
		* reborncoreAPI|Power (2.13.1.25) from RebornCore-1.11.2-2.13.1.25-universal.jar
		* reborncoreAPI|Recipe (2.13.1.25) from RebornCore-1.11.2-2.13.1.25-universal.jar
		* reborncoreAPI|Tile (2.13.1.25) from RebornCore-1.11.2-2.13.1.25-universal.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
		* StorageDrawersAPI|event (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.1.0.jar
		* StorageDrawersAPI|pack (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.1.0.jar
		* StorageDrawersAPI|registry (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.1.0.jar
		* StorageDrawersAPI|render (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.1.0.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from refinedstorage-1.3.5.jar
		* StorageDrawersAPI|storage-attribute (1.10.2-1.3.0) from StorageDrawers-1.11.2-4.1.0.jar
		* techrebornAPI (2.1.1.42) from TechReborn-1.11.2-2.1.1.42-universal.jar
		* TerraqueousAPI (1.0) from terraqueous-1.11.0-1.3.4.jar
		* TerraqueousAPI|Cloud (1.0) from terraqueous-1.11.0-1.3.4.jar
		* TerraqueousAPI|Machines (1.0) from terraqueous-1.11.0-1.3.4.jar
		* TerraqueousAPI|Plant (1.0) from terraqueous-1.11.0-1.3.4.jar
		* valkyrielib.api (1.11.2-0.11.0b) from valkyrielib-1.11.2-0.11.0b.jar
	Launched Version: forge-13.20.0.2222
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.54, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD Phenom(tm) II X4 840 Processor
	OptiFine Version: OptiFine_1.11.2_HD_U_B6
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 353.54
	OpenGlRenderer: GeForce GTX 750 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by elucent** [comment]
Should be fixed now.
