### ISSUE TITLE
[Suggestion] allow pumps and ember transmitters to be redstone inverted

### ISSUE THREAD

**Issue by theredghostwolf** [RootsTeam/Embers#96]
i find that having a lever on everything messes up my wiring and looks pretty ugly when you have alot of them in random spots.

also there is alot of stuff i want to be constantly pumping items / ember / fluid so would be nice if i could have it be turned on by default and it would stop pumping once a signal is applied.

maybe give the hammer different modes by shift-clicking the air with it, like linking mode and redstone mode.

**Comment by elucent** [comment]
I'd rather not. I think having to work around redstone is part of the mod's automation style. Embers machines aren't made to be very configurable. For the aesthetics complaint, I'm considering making a new kind of lever in the future to better fit the mod's style. Embers is just designed to have some design limitations -- I don't want to become Ender IO.
