### ISSUE TITLE
Alchemy recipes sometimes require below minimum values of ash to complete

### ISSUE THREAD

**Issue by TBone311xXx** [RootsTeam/Embers#97]
I have found that when attempting to create ashen fabric, I am unable to do so. The values I use for the pedestals are 8 silver, and 16 iron. When I increase the values of either, the accuracy percentage decreases, and decreasing iron while increasing silver also decreases the accuracy. The trend that looks to lead towards 100% accuracy is to lessen the ash in the silver aspectus, while retaining 16 in the iron aspectus, But that is impossible as the minimum ash required to recognize the recipe is seemingly 24 ash. 

Is there any way in which I could potentially debug this and see what the values of ash are that are necessary to complete the ritual? If you need more information, I will be happy to supply it, And for reference, this is on a server with a world seed of "8387977158399674618".

**Comment by elucent** [comment]
I've changed the way accuracy is displayed. It should allow you to see the issue much better, once I release a version that is. It will be for 1.11.2, as that is where my development is focused these days.

**Comment by elucent** [comment]
Probably shouldn't close the issue. :P

**Comment by VallenFrostweaver** [comment]
Is there a fix planned for 1.10.2 for this bug? I can't get the ash combination to make an inflictor gem since it always gives me that 0% accuracy result.

**Comment by elucent** [comment]
I'm going to try to stick to 1.11.2 from here on out unfortunately. If I get around to it, I might implement a change, but I would honestly rather spend the time on Roots 2 or new Embers content.

**Comment by elucent** [comment]
I believe this is fixed for 1.11.2. Since 1.10.2 is essentially an unsupported version at this point, and the 1.11 version is different enough that maintaining both is no longer practical, I will close this issue.
