### ISSUE TITLE
[Bug] Taking damage while full Ashen armor set is equipped and Cloak contains gems causes CTD for Embers 0.104 for Minecraft 1.10.2

### ISSUE THREAD

**Issue by KumquatThaumaturge** [RootsTeam/Embers#99]
Full crash report at pastebin:
http://pastebin.com/WQE3D33D

Minecraft Version: 1.10.2
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_121, Oracle Corporation
Forge 12.18.3.2221
Embers 0.104 for Minecraft 1.10.2

Issue: When full Ashen armor set is equipped and damage is taken with at least one gem socketed in the armor, Minecraft CTDs

To replicate: create superflat creative world, equip full Ashen armor set with at least one gem crafted into the armor, change gamemode to survival, and get attacked by one of the many slimes which spawn. Partially equipping the armor set does not seem to trigger this crash, just so long as at least one piece of the armor set is missing.

Other comments: I originally noticed this issue in a heavily modded world, in which a full ashen armor set crashed the game when the player takes damage regardless of whether or not a gem is socketed into the armor. In an attempt to determine which mod was having compatibility issues with Embers, I removed all of them and then tried to replicate my issue with Embers alone, at which point I WAS able to take damage without crashing if no gems were present in the armor set, but which caused the above issue of crashing WITH gems. I can post the crash reports from heavily modded worlds as well if requested.

I realize that your primary support will be dedicated to the 1.11.2 version of Embers, but in your reddit post explaining your decision to focus on 1.11.2 you also said that you would try and focus any horrendous crashing bugs for 1.10.2. I don't know if this exactly qualifies as it doesn't block off a great deal of Embers content, but I thought I ought to bring it to your attention.

**Comment by VallenFrostweaver** [comment]
I found this to happen if the armor is enchanted and gems are not required. Constant crash on entrance into the world if I was on fire. Not sure if your armor set was enchanted or not as that may be the conflict.

**Comment by elucent** [comment]
Closing this because 1.10.2 is no longer being supported.
